// web/src/ui/MarkdownBody.vue
<script setup>
import { nextTick, onBeforeUnmount, ref, watch } from "vue";
import {
  decorateMarkdownLinks,
  enhanceCodeBlocks,
  renderDrawioIn,
  renderMarkdownWithMath,
  renderMermaidIn,
  enhanceChatImages,
} from "@/utils/markdown";
import { renderEchartsIn } from "@/utils/echarts";
import { renderMathIn } from "@/utils/math";

const props = defineProps({
  content: { type: String, default: "" },
  streaming: Boolean,
  plain: Boolean,
  modelProvider: { type: String, default: "" },
  modelName: { type: String, default: "" },
});

const emit = defineEmits(["mermaid-fixed"]);

const root = ref(null);
const html = ref("");

let renderGen = 0;
let debounceTimer = null;

async function repairMermaid(source, error) {
  const resp = await fetch("/api/mermaid/repair", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      source,
      error,
      model_provider: props.modelProvider || undefined,
      model_name: props.modelName || undefined,
    }),
  });
  let json = null;
  try {
    json = await resp.json();
  } catch {
    throw new Error(`mermaid repair HTTP ${resp.status}`);
  }
  if (!resp.ok || !json?.ok) {
    throw new Error(json?.error?.message || `mermaid repair failed (${resp.status})`);
  }
  return json.data?.source || "";
}

function onFixed({ from, to }) {
  emit("mermaid-fixed", { from, to });
}

async function paint() {
  if (props.plain) {
    html.value = "";
    return;
  }
  const gen = ++renderGen;
  const nextHtml = await renderMarkdownWithMath(props.content, { streaming: props.streaming });
  if (gen !== renderGen) return;
  html.value = nextHtml;
  await nextTick();
  if (gen !== renderGen || !root.value) return;

  root.value.querySelectorAll(".echarts-block").forEach((block) => {
    if (block._nlmChart) {
      try {
        block._nlmChart.dispose();
      } catch {
        /* ignore */
      }
      block._nlmChart = null;
    }
  });

  decorateMarkdownLinks(root.value);
  enhanceCodeBlocks(root.value);
  enhanceChatImages(root.value);
  // Fallback for any unprotected delimiters
  await renderMathIn(root.value);
  await Promise.all([
    renderMermaidIn(root.value, {
      streaming: false,
      repair: props.streaming ? null : repairMermaid,
      onFixed,
    }),
    renderEchartsIn(root.value, { streaming: props.streaming }),
  ]);
  if (!props.streaming) {
    await renderDrawioIn(root.value, { streaming: false });
  }
}

watch(
  () => [props.content, props.streaming, props.plain],
  () => {
    if (debounceTimer) clearTimeout(debounceTimer);
    const wait = props.streaming ? 280 : 0;
    debounceTimer = setTimeout(() => {
      debounceTimer = null;
      paint();
    }, wait);
  },
  { immediate: true }
);

onBeforeUnmount(() => {
  if (debounceTimer) clearTimeout(debounceTimer);
  root.value?.querySelectorAll?.(".echarts-block").forEach((block) => {
    try {
      block._nlmChart?.dispose?.();
    } catch {
      /* ignore */
    }
  });
});
</script>

<template>
  <div v-if="plain" class="nlm-md plain">{{ content }}</div>
  <div v-else ref="root" class="nlm-md md body" v-html="html" />
</template>

// web/src/components/chat/MarkdownBody.tsx
import { useEffect, useRef, useState } from "react";

import { repairMermaid as repairMermaidApi } from "@/api/endpoints";
import {
  enhanceMarkdownRoot,
  renderDrawioIn,
  renderEchartsIn,
  renderMarkdownWithMath,
  renderMathIn,
  renderMermaidIn,
} from "@/lib/markdown";
import { cn } from "@/lib/utils";

export type MarkdownBodyProps = {
  content?: string;
  streaming?: boolean;
  plain?: boolean;
  modelProvider?: string;
  modelName?: string;
  className?: string;
  onMermaidFixed?: (args: { from: string; to: string }) => void;
};

export function MarkdownBody({
  content = "",
  streaming = false,
  plain = false,
  modelProvider = "",
  modelName = "",
  className,
  onMermaidFixed,
}: MarkdownBodyProps) {
  const rootRef = useRef<HTMLDivElement>(null);
  const [html, setHtml] = useState("");
  const genRef = useRef(0);
  const onFixedRef = useRef(onMermaidFixed);
  onFixedRef.current = onMermaidFixed;

  useEffect(() => {
    if (plain) {
      setHtml("");
      return;
    }

    let cancelled = false;
    let debounceTimer: ReturnType<typeof setTimeout> | null = null;
    const wait = streaming ? 280 : 0;

    const paint = async () => {
      const gen = ++genRef.current;
      const nextHtml = await renderMarkdownWithMath(content, { streaming });
      if (cancelled || gen !== genRef.current) return;
      setHtml(nextHtml);

      // Wait for DOM to commit before enhancing
      await Promise.resolve();
      await Promise.resolve();
      if (cancelled || gen !== genRef.current) return;
      const root = rootRef.current;
      if (!root) return;

      root.querySelectorAll(".echarts-block").forEach((block) => {
        const el = block as HTMLElement & { _nlmChart?: { dispose?: () => void } | null };
        if (el._nlmChart) {
          try {
            el._nlmChart.dispose?.();
          } catch {
            /* ignore */
          }
          el._nlmChart = null;
        }
      });

      enhanceMarkdownRoot(root);
      await renderMathIn(root);

      const repair = streaming
        ? null
        : async (source: string, error: string) => {
            const data = await repairMermaidApi({
              source,
              error,
              model_provider: modelProvider || undefined,
              model_name: modelName || undefined,
            });
            return data?.source || "";
          };

      await Promise.all([
        renderMermaidIn(root, {
          streaming: false,
          repair,
          onFixed: (args) => onFixedRef.current?.(args),
        }),
        renderEchartsIn(root, { streaming }),
      ]);
      if (!streaming) {
        await renderDrawioIn(root, { streaming: false });
      }
    };

    debounceTimer = setTimeout(() => {
      debounceTimer = null;
      void paint();
    }, wait);

    return () => {
      cancelled = true;
      if (debounceTimer) clearTimeout(debounceTimer);
      rootRef.current?.querySelectorAll?.(".echarts-block").forEach((block) => {
        const el = block as HTMLElement & { _nlmChart?: { dispose?: () => void } | null };
        try {
          el._nlmChart?.dispose?.();
        } catch {
          /* ignore */
        }
      });
    };
  }, [content, streaming, plain, modelProvider, modelName]);

  if (plain) {
    return (
      <div className={cn("nlm-md plain whitespace-pre-wrap break-words text-[13px]", className)}>
        {content}
      </div>
    );
  }

  return (
    <div
      ref={rootRef}
      className={cn("nlm-md md body text-[13px] leading-relaxed break-words [&_*:first-child]:mt-0 [&_*:last-child]:mb-0", className)}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

export default MarkdownBody;
