// web/src/components/MessageBubble.vue
<script setup>
import { formatUsageLine } from "@/utils/pretty";
import {
  cacheHitRate,
  estimateCostCny,
  formatCacheHit,
  formatCny,
  formatDurationMs,
  formatTokenCount,
  resolveModelRate,
} from "@/utils/pricing";
import { computed, ref } from "vue";
import ActivityHint from "@/components/ActivityHint.vue";

const props = defineProps({
  item: { type: Object, required: true },
  modelProvider: { type: String, default: "" },
  modelName: { type: String, default: "" },
});

const emit = defineEmits(["accept-plan"]);

const openUsage = ref(false);

/** Caret only while tokens are streaming — not during tool/subagent/wait phases. */
const showCaret = computed(() => {
  if (!props.item.streaming) return false;
  const phase = props.item.activity?.phase;
  return !phase || phase === "stream";
});

const usageSummary = computed(() => {
  if (!props.item.usage) return "";
  return formatUsageLine(props.item.usage, {
    modelName: props.modelName,
    providerId: props.modelProvider,
  });
});

const usageDetail = computed(() => {
  const u = props.item.usage;
  if (!u) return null;
  const cost = estimateCostCny(u, {
    modelName: props.modelName,
    providerId: props.modelProvider,
  });
  const cache = formatCacheHit(u);
  const rate = resolveModelRate(props.modelName, props.modelProvider);
  return {
    prompt: Number(u.prompt_tokens || 0),
    completion: Number(u.completion_tokens || 0),
    total: Number(u.total_tokens || (u.prompt_tokens || 0) + (u.completion_tokens || 0)),
    duration: formatDurationMs(u.duration_ms) || "—",
    cached: Number(u.cached_tokens || 0),
    cacheText: cache.cached > 0 ? `${formatTokenCount(cache.cached)} · ${cacheHitRate(u).toFixed(1)}%` : "0",
    costText: formatCny(cost.yuan),
    rateText: `输入 ¥${rate.input}/M · 输出 ¥${rate.output}/M · 缓存 ¥${rate.cache}/M`,
    estimated: !!u.estimated,
  };
});

function onMermaidFixed({ from, to }) {
  if (!from || !to || from === to) return;
  const content = props.item.content || "";
  if (!content.includes(from)) return;
  props.item.content = content.replace(from, to);
}
</script>

<template>
  <div class="msg" :class="[item.role, { live: item.live || item.streaming }]">
    <MarkdownBody
      v-if="item.content"
      class="body"
      :content="item.content"
      :streaming="showCaret"
      :plain="!item.rich"
      :model-provider="modelProvider"
      :model-name="modelName"
      @mermaid-fixed="onMermaidFixed"
    />
    <ActivityHint
      v-if="item.activity && (item.streaming || item.live)"
      embedded
      :active="true"
      :phase="item.activity.phase"
      :label="item.activity.label"
      :detail="item.activity.detail"
      :started-at="item.activity.startedAt"
    />
    <button
      v-if="item.planReady && item.role === 'assistant' && !item.streaming && !item.live"
      type="button"
      class="accept-plan-btn"
      @click="emit('accept-plan', item)"
    >
      接受计划并执行
    </button>
    <button
      v-if="item.usage"
      type="button"
      class="token-badge clickable"
      :title="'点击查看明细'"
      @click="openUsage = !openUsage"
    >
      {{ usageSummary }}
    </button>
    <div v-if="openUsage && usageDetail" class="turn-usage">
      <div class="usage-row"><span>输入</span><strong>{{ usageDetail.prompt }}</strong></div>
      <div class="usage-row"><span>输出</span><strong>{{ usageDetail.completion }}</strong></div>
      <div class="usage-row"><span>合计</span><strong>{{ usageDetail.total }}</strong></div>
      <div class="usage-row"><span>耗时</span><strong>{{ usageDetail.duration }}</strong></div>
      <div class="usage-row"><span>缓存命中</span><strong>{{ usageDetail.cacheText }}</strong></div>
      <div class="usage-row"><span>估算费用</span><strong>{{ usageDetail.costText }}</strong></div>
      <p class="rail-hint">{{ usageDetail.rateText }}</p>
      <p v-if="usageDetail.estimated" class="rail-hint">含估算 token（接口未返回 usage）</p>
    </div>
  </div>
</template>

<style scoped>
/* Long user messages stay in a capped viewport; wheel to scroll (scrollbar hidden globally). */
.msg.user :deep(.body) {
  max-height: 10.5em;
  overflow-y: auto;
  overscroll-behavior: contain;
  scrollbar-width: none;
  -ms-overflow-style: none;
}
.msg.user :deep(.body)::-webkit-scrollbar {
  width: 0;
  height: 0;
  display: none;
}
.token-badge.clickable {
  cursor: pointer;
  border: 0;
  background: transparent;
  padding: 0;
  max-width: 100%;
  text-align: left;
  white-space: normal;
  line-height: 1.35;
}
.accept-plan-btn {
  margin-top: 8px;
  height: 30px;
  padding: 0 12px;
  border-radius: 8px;
  border: 1px solid rgba(58, 156, 240, 0.45);
  background: rgba(58, 156, 240, 0.12);
  color: var(--accent);
  font: inherit;
  font-size: var(--fs-xs);
  cursor: pointer;
}
.accept-plan-btn:hover {
  filter: brightness(1.08);
}
.token-badge.clickable:hover {
  color: var(--ink);
}
.turn-usage {
  margin-top: 6px;
  padding: 7px 8px;
  border-radius: 7px;
  border: 1px solid var(--line);
  background: rgba(255, 255, 255, 0.03);
  max-width: 280px;
}
.usage-row {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  font-size: var(--fs-xs);
  padding: 2px 0;
}
.usage-row strong {
  font-family: var(--mono);
  font-weight: 500;
}
.rail-hint {
  margin: 4px 0 0;
  font-size: 10px;
  color: var(--muted);
  line-height: 1.35;
}
</style>

// web/src/components/chat/MessageBubble.tsx
import { memo, useEffect, useMemo, useState } from "react";
import { Check, Copy } from "lucide-react";
import { toast } from "sonner";

import { ActivityHint } from "@/components/chat/ActivityHint";
import { MarkdownBody } from "@/components/chat/MarkdownBody";
import { ThinkingFold } from "@/components/chat/ThinkingFold";
import { Button } from "@/components/ui/button";
import {
  cacheHitRate,
  estimateCostCny,
  formatCacheHit,
  formatCny,
  formatDurationMs,
  formatTokenCount,
  formatUsageLine,
  resolveModelRate,
} from "@/lib/pricing";
import { cn } from "@/lib/utils";

export type MessageBubbleItem = {
  role: string;
  content?: string;
  reasoning?: string;
  rich?: boolean;
  streaming?: boolean;
  live?: boolean;
  usage?: any;
  modelName?: string;
  modelProvider?: string;
  activity?: {
    phase?: string;
    label?: string;
    detail?: string;
    startedAt?: number;
  } | null;
  planReady?: boolean;
};

export type MessageBubbleProps = {
  item: MessageBubbleItem;
  modelProvider?: string;
  modelName?: string;
  onAcceptPlan?: (item: MessageBubbleItem) => void;
  className?: string;
};

export const MessageBubble = memo(function MessageBubble({
  item,
  modelProvider = "",
  modelName = "",
  onAcceptPlan,
  className,
}: MessageBubbleProps) {
  const [openUsage, setOpenUsage] = useState(false);
  const [content, setContent] = useState(item.content || "");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setContent(item.content || "");
  }, [item.content]);

  const resolvedModel = item.modelName || modelName || "";
  const resolvedProvider = item.modelProvider || modelProvider || "";

  const showCaret = useMemo(() => {
    if (!item.streaming) return false;
    const phase = item.activity?.phase;
    // Keep caret while model/stream so text paints live next to the spinner.
    return !phase || phase === "stream" || phase === "model";
  }, [item.streaming, item.activity?.phase]);

  const usageSummary = useMemo(() => {
    if (!item.usage) return "";
    return formatUsageLine(item.usage, {
      modelName: resolvedModel,
      providerId: resolvedProvider,
    });
  }, [item.usage, resolvedModel, resolvedProvider]);

  const usageDetail = useMemo(() => {
    const u = item.usage;
    if (!u) return null;
    const cost = estimateCostCny(u, { modelName: resolvedModel, providerId: resolvedProvider });
    const cache = formatCacheHit(u);
    const rate = resolveModelRate(resolvedModel, resolvedProvider);
    return {
      model: resolvedModel || "—",
      prompt: formatTokenCount(Number(u.prompt_tokens || 0)),
      completion: formatTokenCount(Number(u.completion_tokens || 0)),
      total: formatTokenCount(
        Number(u.total_tokens || (u.prompt_tokens || 0) + (u.completion_tokens || 0)),
      ),
      duration: formatDurationMs(u.duration_ms) || "—",
      cacheText:
        cache.cached > 0
          ? `${formatTokenCount(cache.cached)} · ${cacheHitRate(u).toFixed(1)}%`
          : "0",
      costText: formatCny(cost.yuan),
      rateText: `输入 ¥${rate.input}/M · 输出 ¥${rate.output}/M · 缓存 ¥${rate.cache}/M`,
      estimated: !!u.estimated,
    };
  }, [item.usage, resolvedModel, resolvedProvider]);

  function onMermaidFixed({ from, to }: { from: string; to: string }) {
    if (!from || !to || from === to) return;
    if (!content.includes(from)) return;
    const next = content.replace(from, to);
    item.content = next;
    setContent(next);
  }

  async function copyFullText() {
    const text = (content || "").trim();
    if (!text) {
      toast.error("没有可复制的内容");
      return;
    }
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast.success("已复制全文");
      window.setTimeout(() => setCopied(false), 1600);
    } catch {
      toast.error("复制失败");
    }
  }

  const isUser = item.role === "user";
  const showFooter =
    !isUser && !item.streaming && !item.live && !!(content || "").trim();

  return (
    <div
      className={cn(
        "msg w-fit max-w-full animate-in fade-in duration-150 rounded-xl border px-3.5 py-2.5",
        isUser
          ? "ml-auto max-w-[min(92%,720px)] self-end rounded-br-sm border-primary/25 bg-primary/10"
          : "w-full self-start rounded-bl-sm border-border bg-card/40",
        (item.live || item.streaming) && "live",
        className,
      )}
    >
      {!isUser && (item.reasoning || (item.streaming && item.activity?.phase === "model")) ? (
        <ThinkingFold
          text={item.reasoning || ""}
          streaming={!!item.streaming && !(content || "").trim()}
        />
      ) : null}

      {content ? (
        <MarkdownBody
          className={cn(
            "body",
            isUser && "max-h-[10.5em] overflow-y-auto overscroll-contain [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",
          )}
          content={content}
          streaming={!!item.streaming && showCaret}
          plain={!item.rich}
          modelProvider={resolvedProvider}
          modelName={resolvedModel}
          onMermaidFixed={onMermaidFixed}
        />
      ) : null}

      {item.activity && (item.streaming || item.live) ? (
        <ActivityHint
          embedded
          active
          phase={item.activity.phase}
          label={item.activity.label}
          detail={item.activity.detail}
          startedAt={item.activity.startedAt}
        />
      ) : null}

      {item.planReady && item.role === "assistant" && !item.streaming && !item.live ? (
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="mt-2 h-7 border-primary/45 bg-primary/10 px-3 text-xs text-primary hover:bg-primary/15"
          onClick={() => onAcceptPlan?.(item)}
        >
          接受计划并执行
        </Button>
      ) : null}

      {showFooter ? (
        <div className="mt-1.5 flex items-end gap-2">
          <div className="min-w-0 flex-1">
            {item.usage ? (
              <button
                type="button"
                className="token-badge max-w-full cursor-pointer border-0 bg-transparent p-0 text-left font-mono text-[11px] leading-snug text-muted-foreground hover:text-foreground"
                title="点击查看明细"
                onClick={() => setOpenUsage((v) => !v)}
              >
                {usageSummary}
              </button>
            ) : resolvedModel ? (
              <span className="font-mono text-[11px] text-muted-foreground">{resolvedModel}</span>
            ) : null}

            {openUsage && usageDetail ? (
              <div className="mt-1.5 max-w-[300px] rounded-md border border-border bg-background/50 px-2 py-1.5">
                {(
                  [
                    ["模型", usageDetail.model],
                    ["输入", usageDetail.prompt],
                    ["输出", usageDetail.completion],
                    ["合计", usageDetail.total],
                    ["耗时", usageDetail.duration],
                    ["缓存命中", usageDetail.cacheText],
                    ["估算费用", usageDetail.costText],
                  ] as const
                ).map(([label, val]) => (
                  <div key={label} className="flex justify-between gap-3 py-0.5 text-[11px]">
                    <span className="text-muted-foreground">{label}</span>
                    <strong className="max-w-[180px] truncate font-mono font-medium" title={String(val)}>
                      {val}
                    </strong>
                  </div>
                ))}
                <p className="mt-1 text-[10px] leading-snug text-muted-foreground">{usageDetail.rateText}</p>
                {usageDetail.estimated ? (
                  <p className="mt-0.5 text-[10px] leading-snug text-muted-foreground">
                    含估算 token（接口未返回 usage）
                  </p>
                ) : null}
              </div>
            ) : null}
          </div>

          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="size-7 shrink-0 text-muted-foreground hover:text-foreground"
            title="复制全文"
            aria-label="复制全文"
            onClick={() => void copyFullText()}
          >
            {copied ? <Check className="size-3.5 text-emerald-400" /> : <Copy className="size-3.5" />}
          </Button>
        </div>
      ) : item.usage ? (
        <button
          type="button"
          className="token-badge mt-1 max-w-full cursor-pointer border-0 bg-transparent p-0 text-left font-mono text-[11px] leading-snug text-muted-foreground hover:text-foreground"
          title="点击查看明细"
          onClick={() => setOpenUsage((v) => !v)}
        >
          {usageSummary}
        </button>
      ) : null}
    </div>
  );
});

export default MessageBubble;
