// web/src/components/ToolCallGroup.vue
<script setup>
import { computed, ref } from "vue";
import ToolCard from "./ToolCard.vue";

const props = defineProps({
  tools: { type: Array, default: () => [] },
});
const emit = defineEmits(["inspect"]);

const open = ref(false);

function shortName(name) {
  const raw = String(name || "tool");
  return raw.replace(/^builtin_workspace_/, "").replace(/^cli_/, "").split(".").pop();
}

const summaryLabel = computed(() => {
  const names = props.tools.map((t) => shortName(t.name));
  const unique = [];
  for (const n of names) {
    if (!unique.includes(n)) unique.push(n);
  }
  const preview = unique.slice(0, 4).join(" · ");
  const n = props.tools.length;
  if (n <= 1) return preview || "tool";
  return `${n} 个工具 · ${preview}${unique.length > 4 ? "…" : ""}`;
});

const hasFail = computed(() =>
  props.tools.some((t) => t.status === "fail" || t.error != null || t.success === false)
);
const pending = computed(() =>
  props.tools.some((t) => t.result == null && t.error == null && t.success == null)
);
</script>

<template>
  <details
    class="tool-group"
    :class="{ fail: hasFail, ok: !hasFail && !pending, pending }"
    :open="open"
    @toggle="open = $event.target.open"
  >
    <summary>
      <span class="tool-chevron" aria-hidden="true" />
      <span class="tool-badge">{{ pending ? "RUN" : hasFail ? "ERR" : "TOOLS" }}</span>
      <span class="tool-name">{{ summaryLabel }}</span>
      <span v-if="pending" class="tool-meta">运行中</span>
      <span v-else-if="hasFail" class="tool-meta">有失败</span>
    </summary>
    <div class="tool-group-body">
      <ToolCard
        v-for="t in tools"
        :key="t.id"
        :item="t"
        nested
        @inspect="emit('inspect', $event)"
      />
    </div>
  </details>
</template>

<style scoped>
.tool-group {
  align-self: flex-start;
  width: fit-content;
  max-width: min(100%, 560px);
  animation: fade 180ms ease both;
}

.tool-group summary {
  list-style: none;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  gap: 7px;
  padding: 5px 10px;
  font-size: var(--fs-sm);
  font-weight: 500;
  user-select: none;
  border: 1px solid var(--line);
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.04);
  color: var(--muted);
}

.tool-group summary::-webkit-details-marker {
  display: none;
}

.tool-group summary:hover {
  color: var(--ink);
  border-color: rgba(255, 255, 255, 0.16);
}

.tool-group.ok summary {
  border-color: rgba(43, 184, 160, 0.28);
}

.tool-group.fail summary {
  border-color: rgba(224, 112, 112, 0.35);
}

.tool-group.pending summary {
  border-color: rgba(201, 162, 39, 0.35);
}

.tool-group[open] {
  width: min(100%, 560px);
  border: 1px solid rgba(201, 162, 39, 0.22);
  background: rgba(201, 162, 39, 0.04);
  border-radius: var(--radius);
}

.tool-group[open] summary {
  display: flex;
  width: 100%;
  border: 0;
  border-radius: 0;
  background: transparent;
  color: var(--ink);
}

.tool-group-body {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding: 2px 10px 10px;
}

.tool-badge {
  font-family: var(--mono);
  font-size: var(--fs-xs);
  color: var(--tool);
  background: rgba(201, 162, 39, 0.12);
  border-radius: 4px;
  padding: 1px 6px;
}

.tool-name {
  font-family: var(--mono);
  font-size: var(--fs-sm);
}

.tool-meta {
  margin-left: auto;
  color: var(--muted);
  font-size: var(--fs-xs);
}
</style>

// web/src/components/chat/ToolCallGroup.tsx
import { useMemo, useState } from "react";
import { ChevronRight } from "lucide-react";

import { ToolCard } from "@/components/chat/ToolCard";
import { Badge } from "@/components/ui/badge";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import type { ToolCardItem } from "@/components/tools/toolRegistry";
import { cn } from "@/lib/utils";

export type ToolCallGroupProps = {
  tools: ToolCardItem[];
  onInspect?: (activityId: string) => void;
  className?: string;
};

function shortName(name?: string) {
  const raw = String(name || "tool");
  return raw.replace(/^builtin_workspace_/, "").replace(/^cli_/, "").split(".").pop();
}

export function ToolCallGroup({ tools, onInspect, className }: ToolCallGroupProps) {
  const [open, setOpen] = useState(false);

  const summaryLabel = useMemo(() => {
    const names = tools.map((t) => shortName(t.name));
    const unique: string[] = [];
    for (const n of names) {
      if (n && !unique.includes(n)) unique.push(n);
    }
    const preview = unique.slice(0, 4).join(" · ");
    const n = tools.length;
    if (n <= 1) return preview || "tool";
    return `${n} 个工具 · ${preview}${unique.length > 4 ? "…" : ""}`;
  }, [tools]);

  const hasFail = tools.some(
    (t) => t.status === "fail" || t.error != null || (t as any).success === false,
  );
  const pending = tools.some(
    (t) => t.result == null && t.error == null && (t as any).success == null,
  );

  return (
    <Collapsible
      open={open}
      onOpenChange={setOpen}
      className={cn(
        "tool-group w-fit max-w-[min(100%,560px)] self-start animate-in fade-in duration-150",
        open &&
          "w-[min(100%,560px)] rounded-lg border border-[hsl(var(--tool))]/25 bg-[hsl(var(--tool))]/5",
        className,
      )}
    >
      <CollapsibleTrigger asChild>
        <button
          type="button"
          className={cn(
            "inline-flex items-center gap-1.5 rounded-full border border-border bg-white/5 px-2.5 py-1 text-sm font-medium text-muted-foreground",
            "hover:border-white/15 hover:text-foreground",
            open && "flex w-full rounded-none border-0 bg-transparent text-foreground",
            !hasFail && !pending && "border-teal/30",
            hasFail && "border-destructive/35",
            pending && "border-[hsl(var(--tool))]/35",
          )}
        >
          <ChevronRight
            className={cn("size-3.5 shrink-0 transition-transform", open && "rotate-90")}
            aria-hidden
          />
          <Badge
            variant="outline"
            className="h-5 border-0 bg-[hsl(var(--tool))]/15 px-1.5 font-mono text-[10px] text-[hsl(var(--tool))]"
          >
            {pending ? "RUN" : hasFail ? "ERR" : "TOOLS"}
          </Badge>
          <span className="min-w-0 truncate font-mono text-sm">{summaryLabel}</span>
          {pending ? (
            <span className="ml-auto text-xs text-muted-foreground">运行中</span>
          ) : hasFail ? (
            <span className="ml-auto text-xs text-muted-foreground">有失败</span>
          ) : null}
        </button>
      </CollapsibleTrigger>
      <CollapsibleContent className="flex flex-col gap-1.5 px-2.5 pb-2.5 pt-0.5">
        {tools.map((t) => (
          <ToolCard
            key={(t as any).id || t.callId || t.name}
            item={t}
            nested
            onInspect={onInspect}
          />
        ))}
      </CollapsibleContent>
    </Collapsible>
  );
}

export default ToolCallGroup;
