// web/src/components/WebSearchToolCard.vue
<script setup>
import { computed } from "vue";
import { pretty } from "@/utils/pretty";
import GenericToolCard from "./GenericToolCard.vue";

const props = defineProps({
  item: { type: Object, required: true },
  nested: { type: Boolean, default: false },
});
defineEmits(["inspect"]);

const searchPayload = computed(() => {
  const raw = props.item.result;
  if (!raw) return null;
  let data = raw;
  if (typeof raw === "string") {
    try {
      data = JSON.parse(raw);
    } catch {
      return null;
    }
  }
  if (data && typeof data === "object" && data.value && !data.results) {
    data = data.value;
  }
  if (!data || typeof data !== "object" || !Array.isArray(data.results)) return null;
  return data;
});

const results = computed(() => searchPayload.value?.results || []);
</script>

<template>
  <GenericToolCard
    v-if="!searchPayload"
    :item="item"
    :nested="nested"
    @inspect="$emit('inspect', $event)"
  />
  <details
    v-else
    class="tool-card ok"
    :class="{ nested }"
    :open="!!item.open"
    @toggle="item.open = $event.target.open"
  >
    <summary>
      <span class="tool-chevron" aria-hidden="true" />
      <span class="tool-badge">SEARCH</span>
      <span class="tool-name">{{ item.name }}</span>
      <span class="tool-meta">
        {{ searchPayload.provider || "web" }} · {{ results.length }} 条
      </span>
    </summary>
    <div class="tool-body">
      <div v-if="item.arguments" class="tool-block">
        <label>Query</label>
        <pre>{{ pretty(item.arguments.query || item.arguments) }}</pre>
      </div>
      <div class="search-results">
        <a
          v-for="(r, i) in results"
          :key="i"
          class="search-hit"
          :href="r.url || '#'"
          target="_blank"
          rel="noopener noreferrer"
        >
          <div class="stitle">{{ r.title || r.url || "result" }}</div>
          <div v-if="r.url" class="surl">{{ r.url }}</div>
          <div v-if="r.snippet" class="ssnip">{{ r.snippet }}</div>
        </a>
      </div>
      <div class="tool-actions">
        <button
          v-if="item.activityId"
          type="button"
          class="tool-inspect"
          @click.stop.prevent="$emit('inspect', item.activityId)"
        >
          查看活动
        </button>
      </div>
    </div>
  </details>
</template>

<style scoped>
.search-results {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.search-hit {
  display: block;
  text-decoration: none;
  color: inherit;
  border: 1px solid var(--line);
  border-radius: 8px;
  padding: 7px 8px;
  background: rgba(0, 0, 0, 0.18);
}
.search-hit:hover {
  border-color: rgba(58, 156, 240, 0.4);
}
.stitle {
  font-size: var(--fs-sm);
  font-weight: 600;
  color: #7eb8f5;
}
.surl {
  font-family: var(--mono);
  font-size: 10px;
  color: var(--teal);
  margin-top: 2px;
  word-break: break-all;
}
.ssnip {
  margin-top: 4px;
  font-size: var(--fs-xs);
  color: var(--muted);
  line-height: 1.4;
}
.tool-actions {
  display: flex;
  justify-content: flex-end;
}
.tool-inspect {
  border: 1px solid var(--line);
  background: transparent;
  color: var(--muted);
  font: inherit;
  font-size: var(--fs-xs);
  border-radius: 6px;
  padding: 3px 8px;
  cursor: pointer;
}
</style>

// web/src/components/tools/WebSearchToolCard.tsx
import { useMemo, useState } from "react";
import { ChevronRight } from "lucide-react";

import { GenericToolCard, type GenericToolCardProps } from "@/components/tools/GenericToolCard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { pretty } from "@/lib/pretty";
import { cn } from "@/lib/utils";

function parseSearchPayload(raw: unknown) {
  if (!raw) return null;
  let data: any = raw;
  if (typeof raw === "string") {
    try {
      data = JSON.parse(raw);
    } catch {
      return null;
    }
  }
  if (data && typeof data === "object" && data.value && !data.results) {
    data = data.value;
  }
  if (!data || typeof data !== "object" || !Array.isArray(data.results)) return null;
  return data as { provider?: string; results: any[] };
}

export function WebSearchToolCard({
  item,
  nested = false,
  onInspect,
  onOpenChange,
}: GenericToolCardProps) {
  const searchPayload = useMemo(() => parseSearchPayload(item.result), [item.result]);
  const [open, setOpen] = useState(!!item.open);

  if (!searchPayload) {
    return (
      <GenericToolCard
        item={item}
        nested={nested}
        onInspect={onInspect}
        onOpenChange={onOpenChange}
      />
    );
  }

  const results = searchPayload.results || [];

  return (
    <Collapsible
      open={open}
      onOpenChange={(next) => {
        setOpen(next);
        item.open = next;
        onOpenChange?.(next);
      }}
      className={cn(
        "tool-card ok rounded-lg border border-border/80 bg-card/40 text-sm",
        nested && "ml-2 border-dashed",
      )}
    >
      <CollapsibleTrigger asChild>
        <button
          type="button"
          className={cn(
            "flex w-full items-center gap-1.5 px-2 py-1.5 text-left hover:bg-muted/40",
            open && !nested && "border-b border-border/60",
          )}
        >
          <ChevronRight
            className={cn("size-3.5 shrink-0 text-muted-foreground transition-transform", open && "rotate-90")}
            aria-hidden
          />
          <Badge
            variant="outline"
            className="h-5 shrink-0 px-1.5 font-mono text-[10px] font-medium text-[hsl(var(--tool))]"
          >
            SEARCH
          </Badge>
          <span className="min-w-0 flex-1 truncate font-mono text-xs">{item.name}</span>
          <span className="shrink-0 font-mono text-[10px] text-muted-foreground">
            {searchPayload.provider || "web"} · {results.length} 条
          </span>
        </button>
      </CollapsibleTrigger>
      <CollapsibleContent className="space-y-2 px-2.5 py-2">
        {item.arguments != null ? (
          <div className="space-y-1">
            <div className="text-[10px] uppercase tracking-wide text-muted-foreground">Query</div>
            <pre className="max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-md border border-border bg-background/50 p-2 font-mono text-[10.5px] text-muted-foreground">
              {pretty((item.arguments as any)?.query || item.arguments)}
            </pre>
          </div>
        ) : null}
        <div className="flex flex-col gap-1.5">
          {results.map((r: any, i: number) => (
            <a
              key={i}
              className="block rounded-lg border border-border bg-black/20 px-2 py-1.5 text-inherit no-underline hover:border-primary/40"
              href={r.url || "#"}
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className="text-sm font-semibold text-[#7eb8f5]">{r.title || r.url || "result"}</div>
              {r.url ? (
                <div className="mt-0.5 break-all font-mono text-[10px] text-teal">{r.url}</div>
              ) : null}
              {r.snippet ? (
                <div className="mt-1 text-xs leading-snug text-muted-foreground">{r.snippet}</div>
              ) : null}
            </a>
          ))}
        </div>
        {item.activityId && onInspect ? (
          <div className="flex justify-end">
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="h-6 px-2 text-[10.5px]"
              onClick={(e) => {
                e.stopPropagation();
                onInspect(item.activityId!);
              }}
            >
              查看活动
            </Button>
          </div>
        ) : null}
      </CollapsibleContent>
    </Collapsible>
  );
}

export default WebSearchToolCard;
