// web/src/components/chat/AskUserForm.tsx
import { useEffect, useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

export type AskQuestion = {
  id: string;
  prompt: string;
  options?: { id: string; label: string }[];
  allow_multiple?: boolean;
  allow_custom?: boolean;
};

export type AskUserItem = {
  id?: string;
  title?: string;
  status?: string;
  questions?: AskQuestion[];
  answers?: unknown;
};

export type AskUserFormProps = {
  item: AskUserItem;
  onSubmit?: (ev: { answers: Record<string, { selected: unknown; custom: string | null }> }) => void;
  onDismiss?: () => void;
  className?: string;
};

export function AskUserForm({ item, onSubmit, onDismiss, className }: AskUserFormProps) {
  const pending = item.status === "pending";
  const questions = item.questions || [];

  const [state, setState] = useState<Record<string, string | string[]>>({});
  const [customs, setCustoms] = useState<Record<string, string>>({});

  useEffect(() => {
    setState((prev) => {
      const next = { ...prev };
      for (const q of questions) {
        if (next[q.id] === undefined) next[q.id] = q.allow_multiple ? [] : "";
      }
      return next;
    });
    setCustoms((prev) => {
      const next = { ...prev };
      for (const q of questions) {
        if (next[q.id] === undefined) next[q.id] = "";
      }
      return next;
    });
  }, [questions]);

  const answeredLabel = useMemo(
    () => (item.status === "answered" ? "已回答" : item.status),
    [item.status],
  );

  function toggleMulti(qid: string, oid: string) {
    setState((prev) => {
      const cur = Array.isArray(prev[qid]) ? [...(prev[qid] as string[])] : [];
      const i = cur.indexOf(oid);
      if (i >= 0) cur.splice(i, 1);
      else cur.push(oid);
      return { ...prev, [qid]: cur };
    });
  }

  function handleSubmit() {
    const answers: Record<string, { selected: unknown; custom: string | null }> = {};
    for (const q of questions) {
      const selected = state[q.id];
      const custom = (customs[q.id] || "").trim();
      answers[q.id] = {
        selected: q.allow_multiple ? selected || [] : selected || null,
        custom: q.allow_custom !== false ? custom || null : null,
      };
    }
    onSubmit?.({ answers });
  }

  return (
    <div
      className={cn(
        "grid max-w-[min(100%,720px)] gap-2.5 rounded-[10px] border border-primary/35 bg-primary/10 px-3 py-2.5",
        item.status === "answered" && "opacity-85",
        className,
      )}
    >
      <div className="flex items-center gap-2 text-sm">
        <span className="text-xs font-bold text-primary">询问</span>
        <span className="font-semibold text-foreground">{item.title || "需要你的确认"}</span>
        {!pending ? <span className="ml-auto text-xs text-muted-foreground">{answeredLabel}</span> : null}
      </div>

      {questions.map((q) => (
        <div key={q.id} className="grid gap-1.5 border-t border-white/5 pt-1">
          <div className="text-sm text-foreground">{q.prompt}</div>
          {(q.options || []).length > 0 ? (
            <div className="grid gap-1">
              {q.options!.map((opt) => (
                <label
                  key={opt.id}
                  className="flex cursor-pointer items-start gap-2 text-xs text-muted-foreground"
                >
                  {q.allow_multiple ? (
                    <Checkbox
                      disabled={!pending}
                      checked={(Array.isArray(state[q.id]) ? (state[q.id] as string[]) : []).includes(
                        opt.id,
                      )}
                      onCheckedChange={() => toggleMulti(q.id, opt.id)}
                    />
                  ) : (
                    <input
                      type="radio"
                      disabled={!pending}
                      name={`ask-${item.id || "x"}-${q.id}`}
                      value={opt.id}
                      checked={state[q.id] === opt.id}
                      onChange={() => setState((prev) => ({ ...prev, [q.id]: opt.id }))}
                      className="mt-0.5"
                    />
                  )}
                  <span className="text-foreground">{opt.label}</span>
                </label>
              ))}
            </div>
          ) : null}
          {q.allow_custom !== false ? (
            <Input
              disabled={!pending}
              value={customs[q.id] || ""}
              onChange={(e) => setCustoms((prev) => ({ ...prev, [q.id]: e.target.value }))}
              placeholder="自定义答案（可选）"
              className="h-7 bg-black/30 text-xs"
            />
          ) : null}
        </div>
      ))}

      {pending ? (
        <div className="flex gap-1.5">
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-7 border-primary/55 px-3 text-xs text-primary"
            onClick={handleSubmit}
          >
            提交
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-7 px-3 text-xs"
            onClick={() => onDismiss?.()}
          >
            跳过
          </Button>
        </div>
      ) : item.answers ? (
        <pre className="m-0 whitespace-pre-wrap font-mono text-xs text-muted-foreground">
          {JSON.stringify(item.answers, null, 2)}
        </pre>
      ) : null}
    </div>
  );
}

export default AskUserForm;

// web/src/components/AskUserForm.vue
<script setup>
import { computed, reactive, watch } from "vue";

const props = defineProps({
  item: { type: Object, required: true },
});
const emit = defineEmits(["submit", "dismiss"]);

const pending = computed(() => props.item.status === "pending");
const questions = computed(() => props.item.questions || []);

const state = reactive({});
const customs = reactive({});

function ensureState() {
  for (const q of questions.value) {
    if (state[q.id] === undefined) {
      state[q.id] = q.allow_multiple ? [] : "";
    }
    if (customs[q.id] === undefined) customs[q.id] = "";
  }
}
watch(questions, ensureState, { immediate: true, deep: true });

function toggleMulti(qid, oid) {
  const cur = Array.isArray(state[qid]) ? [...state[qid]] : [];
  const i = cur.indexOf(oid);
  if (i >= 0) cur.splice(i, 1);
  else cur.push(oid);
  state[qid] = cur;
}

function onSubmit() {
  const answers = {};
  for (const q of questions.value) {
    const selected = state[q.id];
    const custom = (customs[q.id] || "").trim();
    answers[q.id] = {
      selected: q.allow_multiple ? selected || [] : selected || null,
      custom: q.allow_custom !== false ? custom || null : null,
    };
  }
  emit("submit", { answers });
}
</script>

<template>
  <div class="ask-card" :class="item.status || 'pending'">
    <div class="ask-head">
      <span class="ask-badge">询问</span>
      <span class="ask-title">{{ item.title || "需要你的确认" }}</span>
      <span v-if="!pending" class="ask-state">{{
        item.status === "answered" ? "已回答" : item.status
      }}</span>
    </div>

    <div v-for="q in questions" :key="q.id" class="ask-q">
      <div class="ask-prompt">{{ q.prompt }}</div>
      <div v-if="(q.options || []).length" class="ask-options">
        <label v-for="opt in q.options" :key="opt.id" class="ask-opt">
          <input
            v-if="q.allow_multiple"
            type="checkbox"
            :disabled="!pending"
            :checked="(state[q.id] || []).includes(opt.id)"
            @change="toggleMulti(q.id, opt.id)"
          />
          <input
            v-else
            v-model="state[q.id]"
            type="radio"
            :disabled="!pending"
            :value="opt.id"
            :name="`ask-${item.id}-${q.id}`"
          />
          <span>{{ opt.label }}</span>
        </label>
      </div>
      <input
        v-if="q.allow_custom !== false"
        v-model="customs[q.id]"
        class="ask-custom"
        type="text"
        :disabled="!pending"
        placeholder="自定义答案（可选）"
      />
    </div>

    <div v-if="pending" class="ask-actions">
      <button type="button" class="btn primary" @click="onSubmit">提交</button>
      <button type="button" class="btn" @click="emit('dismiss')">跳过</button>
    </div>
    <pre v-else-if="item.answers" class="ask-result">{{ JSON.stringify(item.answers, null, 2) }}</pre>
  </div>
</template>

<style scoped>
.ask-card {
  border: 1px solid rgba(58, 156, 240, 0.35);
  border-radius: 10px;
  background: rgba(58, 156, 240, 0.08);
  padding: 10px 12px;
  max-width: min(100%, 720px);
  display: grid;
  gap: 10px;
}
.ask-card.answered {
  opacity: 0.85;
}
.ask-head {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: var(--fs-sm);
}
.ask-badge {
  font-weight: 700;
  color: var(--accent);
  font-size: var(--fs-xs);
}
.ask-title {
  color: var(--ink);
  font-weight: 600;
}
.ask-state {
  margin-left: auto;
  color: var(--muted);
  font-size: var(--fs-xs);
}
.ask-q {
  display: grid;
  gap: 6px;
  padding-top: 4px;
  border-top: 1px solid rgba(255, 255, 255, 0.06);
}
.ask-prompt {
  color: var(--ink);
  font-size: var(--fs-sm);
}
.ask-options {
  display: grid;
  gap: 4px;
}
.ask-opt {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  font-size: var(--fs-xs);
  color: var(--muted);
  cursor: pointer;
}
.ask-opt span {
  color: var(--ink);
}
.ask-custom {
  height: 30px;
  border-radius: 6px;
  border: 1px solid var(--line);
  background: rgba(0, 0, 0, 0.28);
  color: var(--ink);
  padding: 0 8px;
  font: inherit;
  font-size: var(--fs-xs);
}
.ask-actions {
  display: flex;
  gap: 6px;
}
.btn {
  height: 28px;
  padding: 0 12px;
  border-radius: 6px;
  border: 1px solid var(--line);
  background: rgba(255, 255, 255, 0.04);
  color: var(--ink);
  font: inherit;
  font-size: var(--fs-xs);
  cursor: pointer;
}
.btn.primary {
  border-color: rgba(58, 156, 240, 0.55);
  color: var(--accent);
}
.ask-result {
  margin: 0;
  font-family: var(--mono);
  font-size: var(--fs-xs);
  color: var(--muted);
  white-space: pre-wrap;
}
</style>
