// web/src/components/chat/ChatMessages.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  type ReactNode,
  type UIEvent,
} from "react";
import { AnimatePresence, motion } from "motion/react";

import { AskUserForm } from "@/components/chat/AskUserForm";
import { MessageBubble } from "@/components/chat/MessageBubble";
import { PlanReviewCard } from "@/components/chat/PlanReviewCard";
import { SubagentCard } from "@/components/chat/SubagentCard";
import { TodoListCard } from "@/components/chat/TodoListCard";
import { ToolApprovalCard } from "@/components/chat/ToolApprovalCard";
import { ToolCallGroup } from "@/components/chat/ToolCallGroup";
import { ToolCard } from "@/components/chat/ToolCard";
import "@/components/tools/registerBuiltinTools";
import { WorkspacePicker } from "@/components/workspace/WorkspacePicker";
import type { TimelineItem } from "@/hooks/useChatTimeline";
import {
  timelineItemMotion,
  timelineItemMotionReduced,
  usePrefersReducedMotion,
} from "@/lib/motion";
import type { Workspace } from "@/types/api";
import { cn } from "@/lib/utils";

export type ChatMessagesProps = {
  items?: TimelineItem[];
  showWorkspacePicker?: boolean;
  modelProvider?: string;
  modelName?: string;
  onInspectTool?: (activityId: string) => void;
  onPickWorkspace?: (meta: Workspace) => void;
  onResolveApproval?: (ev: {
    item: TimelineItem;
    action: string;
  }) => void;
  onResolveAsk?: (ev: {
    item: TimelineItem;
    action: string;
    answers?: Record<string, unknown>;
  }) => void;
  onResolvePlanReview?: (ev: {
    item: TimelineItem;
    action: string;
    feedback?: string;
  }) => void;
  onAcceptPlan?: (item: TimelineItem) => void;
  className?: string;
};

export type ChatMessagesHandle = {
  el: HTMLDivElement | null;
  scrollBottom: () => void;
};

type Block =
  | { kind: "msg" | "approval" | "ask" | "todos" | "plan_review" | "subagent"; id: string; item: TimelineItem }
  | { kind: "tools"; id: string; tools: TimelineItem[] };

function nearBottom(el: HTMLElement, threshold = 80) {
  return el.scrollHeight - el.scrollTop - el.clientHeight < threshold;
}

function buildBlocks(items: TimelineItem[]): Block[] {
  const out: Block[] = [];
  for (const item of items || []) {
    if (
      item.kind === "approval" ||
      item.kind === "ask" ||
      item.kind === "todos" ||
      item.kind === "plan_review"
    ) {
      out.push({ kind: item.kind, id: item.id, item });
      continue;
    }
    if (item.kind === "tool") {
      const last = out[out.length - 1];
      if (last?.kind === "tools") {
        last.tools.push(item);
      } else {
        out.push({ kind: "tools", id: `tg-${item.id}`, tools: [item] });
      }
      continue;
    }
    if (item.kind === "subagent") {
      out.push({ kind: "subagent", id: item.id, item });
      continue;
    }
    if (
      item.kind === "msg" &&
      item.role === "assistant" &&
      !(item.content || "").trim() &&
      !item.activity &&
      !item.streaming &&
      !item.live &&
      !item.planReady
    ) {
      continue;
    }
    out.push({ kind: "msg", id: item.id, item });
  }
  return out;
}

export const ChatMessages = forwardRef<ChatMessagesHandle, ChatMessagesProps>(
  function ChatMessages(
    {
      items = [],
      showWorkspacePicker = false,
      modelProvider = "",
      modelName = "",
      onInspectTool,
      onPickWorkspace,
      onResolveApproval,
      onResolveAsk,
      onResolvePlanReview,
      onAcceptPlan,
      className,
    },
    ref,
  ) {
    const scrollerRef = useRef<HTMLDivElement>(null);
    const followTailRef = useRef(true);
    const reducedMotion = usePrefersReducedMotion();
    const itemMotion = reducedMotion ? timelineItemMotionReduced : timelineItemMotion;

    useImperativeHandle(ref, () => ({
      get el() {
        return scrollerRef.current;
      },
      scrollBottom() {
        followTailRef.current = true;
        const el = scrollerRef.current;
        if (el) el.scrollTop = el.scrollHeight;
      },
    }));

    const blocks = useMemo(() => buildBlocks(items), [items]);

    const maybeStickBottom = useCallback(() => {
      if (!followTailRef.current) return;
      requestAnimationFrame(() => {
        const el = scrollerRef.current;
        if (el) el.scrollTop = el.scrollHeight;
      });
    }, []);

    const stickKey = useMemo(() => {
      const last = items[items.length - 1];
      if (!last) return "";
      if (last.kind === "msg") return `${items.length}|${last.content || ""}`;
      if (last.kind === "subagent")
        return `${items.length}|${last.streamText || ""}|${last.status || ""}`;
      if (last.kind === "tool") return `${items.length}|${last.status || ""}|${last.open ? 1 : 0}`;
      return `${items.length}|${last.id || ""}`;
    }, [items]);

    useEffect(() => {
      const last = items[items.length - 1];
      if (last?.kind === "msg" && last.role === "user") {
        followTailRef.current = true;
      }
      maybeStickBottom();
    }, [stickKey, items, maybeStickBottom]);

    function onScroll(e: UIEvent<HTMLDivElement>) {
      followTailRef.current = nearBottom(e.currentTarget);
    }

    function wrapMotion(id: string, child: ReactNode) {
      return (
        <motion.div key={id} layout={!reducedMotion} {...itemMotion} className="w-full">
          {child}
        </motion.div>
      );
    }

    return (
      <div
        ref={scrollerRef}
        className={cn(
          "messages flex min-h-0 flex-1 flex-col gap-2.5 overflow-y-auto overscroll-contain px-0.5 pb-3 pt-4",
          "[scrollbar-gutter:stable]",
          className,
        )}
        onScroll={onScroll}
      >
        {!items.length ? (
          <div className="empty-state m-auto px-4 py-10 text-center text-muted-foreground animate-in fade-in duration-300">
            <div className="empty-brand mb-2 bg-gradient-to-r from-white via-[#8ec8f5] to-[#6fd4c0] bg-clip-text text-[22px] font-bold tracking-tight text-transparent">
              Nexus Lark Mind
            </div>
            <p className="m-0 text-sm">
              先绑定工作目录，再让 Coding Agent 用 glob / grep / 读写 / shell 在项目里干活。
              Agent 会按任务自行决定是否委派 subagent；飞书、插件坞与 Trajectory 仍是工作台能力。
            </p>
            {showWorkspacePicker ? (
              <WorkspacePicker
                className="empty-ws mt-[18px]"
                compact
                onBound={(meta) => onPickWorkspace?.(meta)}
              />
            ) : null}
          </div>
        ) : null}

        <AnimatePresence initial={false} mode="popLayout">
          {blocks.map((block) => {
            if (block.kind === "msg") {
              return wrapMotion(
                block.id,
                <MessageBubble
                  item={block.item as any}
                  modelProvider={modelProvider}
                  modelName={modelName}
                  onAcceptPlan={() => onAcceptPlan?.(block.item)}
                />,
              );
            }
            if (block.kind === "approval") {
              return wrapMotion(
                block.id,
                <ToolApprovalCard
                  item={block.item as any}
                  onResolve={(ev) =>
                    onResolveApproval?.({ item: block.item, action: ev.action })
                  }
                />,
              );
            }
            if (block.kind === "ask") {
              return wrapMotion(
                block.id,
                <AskUserForm
                  item={block.item as any}
                  onSubmit={(ev) =>
                    onResolveAsk?.({
                      item: block.item,
                      action: "submit",
                      answers: ev.answers as Record<string, unknown> | undefined,
                    })
                  }
                  onDismiss={() => onResolveAsk?.({ item: block.item, action: "deny" })}
                />,
              );
            }
            if (block.kind === "plan_review") {
              return wrapMotion(
                block.id,
                <PlanReviewCard
                  item={block.item as any}
                  modelProvider={modelProvider}
                  modelName={modelName}
                  onResolve={(ev) =>
                    onResolvePlanReview?.({
                      item: block.item,
                      action: ev.action,
                      feedback: ev.feedback || "",
                    })
                  }
                />,
              );
            }
            if (block.kind === "todos") {
              return wrapMotion(block.id, <TodoListCard item={block.item as any} />);
            }
            if (block.kind === "subagent") {
              return wrapMotion(
                block.id,
                <SubagentCard item={block.item as any} onInspect={onInspectTool} />,
              );
            }
            if (block.kind === "tools") {
              if (block.tools.length > 1) {
                return wrapMotion(
                  block.id,
                  <ToolCallGroup tools={block.tools as any} onInspect={onInspectTool} />,
                );
              }
              return wrapMotion(
                block.id,
                <ToolCard item={block.tools[0] as any} onInspect={onInspectTool} />,
              );
            }
            return null;
          })}
        </AnimatePresence>
      </div>
    );
  },
);

export default ChatMessages;

// web/src/components/ChatMessages.vue
<script setup>
import { computed, nextTick, ref, watch } from "vue";
import MessageBubble from "./MessageBubble.vue";
import ToolCard from "./ToolCard.vue";
import ToolCallGroup from "./ToolCallGroup.vue";
import SubagentCard from "./SubagentCard.vue";
import ToolApprovalCard from "./ToolApprovalCard.vue";
import AskUserForm from "./AskUserForm.vue";
import PlanReviewCard from "./PlanReviewCard.vue";
import TodoListCard from "./TodoListCard.vue";
import WorkspacePicker from "./WorkspacePicker.vue";

const props = defineProps({
  items: { type: Array, default: () => [] },
  showWorkspacePicker: { type: Boolean, default: false },
  modelProvider: { type: String, default: "" },
  modelName: { type: String, default: "" },
});
const emit = defineEmits([
  "inspect-tool",
  "pick-workspace",
  "resolve-approval",
  "resolve-ask",
  "resolve-plan-review",
  "accept-plan",
]);

function onApproval(item, ev) {
  emit("resolve-approval", { item, action: ev?.action || "allow" });
}
function onAskSubmit(item, ev) {
  emit("resolve-ask", { item, action: "submit", answers: ev?.answers });
}
function onAskDismiss(item) {
  emit("resolve-ask", { item, action: "deny" });
}
function onPlanReview(item, ev) {
  emit("resolve-plan-review", {
    item,
    action: ev?.action || "deny",
    feedback: ev?.feedback || "",
  });
}

const scroller = ref(null);
/** When false, user scrolled up — do not yank them back during streaming. */
const followTail = ref(true);

/** Collapse consecutive regular tool calls; keep subagents / approval / ask as own cards. */
const blocks = computed(() => {
  const out = [];
  for (const item of props.items || []) {
    if (item.kind === "approval" || item.kind === "ask" || item.kind === "todos" || item.kind === "plan_review") {
      out.push({ kind: item.kind, id: item.id, item });
      continue;
    }
    if (item.kind === "tool") {
      const last = out[out.length - 1];
      if (last?.kind === "tools") {
        last.tools.push(item);
      } else {
        out.push({ kind: "tools", id: `tg-${item.id}`, tools: [item] });
      }
      continue;
    }
    if (item.kind === "subagent") {
      out.push({ kind: "subagent", id: item.id, item });
      continue;
    }
    // Hide ghost assistant shells: empty, not live, no activity hint
    if (
      item.kind === "msg" &&
      item.role === "assistant" &&
      !(item.content || "").trim() &&
      !item.activity &&
      !item.streaming &&
      !item.live &&
      !item.planReady
    ) {
      continue;
    }
    out.push({ kind: "msg", id: item.id, item });
  }
  return out;
});

function nearBottom(el, threshold = 80) {
  if (!el) return true;
  return el.scrollHeight - el.scrollTop - el.clientHeight < threshold;
}

function onScroll() {
  const el = scroller.value;
  if (!el) return;
  followTail.value = nearBottom(el);
}

async function maybeStickBottom() {
  if (!followTail.value) return;
  await nextTick();
  const el = scroller.value;
  if (el) el.scrollTop = el.scrollHeight;
}

watch(() => props.items.length, () => {
  const last = props.items[props.items.length - 1];
  // New user turn → resume stick-to-bottom so the reply is visible.
  if (last?.kind === "msg" && last.role === "user") {
    followTail.value = true;
  }
  maybeStickBottom();
});

watch(
  () => {
    const last = props.items[props.items.length - 1];
    if (!last) return "";
    if (last.kind === "msg") return last.content;
    if (last.kind === "subagent") return `${last.streamText || ""}|${last.status || ""}`;
    if (last.kind === "tool") return `${last.status || ""}|${last.open ? 1 : 0}`;
    return last.id || "";
  },
  () => {
    maybeStickBottom();
  }
);

defineExpose({
  el: scroller,
  scrollBottom() {
    followTail.value = true;
    if (scroller.value) scroller.value.scrollTop = scroller.value.scrollHeight;
  },
});
</script>

<template>
  <div ref="scroller" class="messages" @scroll.passive="onScroll">
    <div v-if="!items.length" class="empty-state">
      <div class="empty-brand">Nexus Lark Mind</div>
      <p>
        先绑定工作目录，再让 Coding Agent 用 glob / grep / 读写 / shell 在项目里干活。
        Agent 会按任务自行决定是否委派 subagent；飞书、插件坞与 Trajectory 仍是工作台能力。
      </p>
      <WorkspacePicker
        v-if="showWorkspacePicker"
        class="empty-ws"
        compact
        @pick="emit('pick-workspace', $event)"
      />
    </div>
    <template v-for="block in blocks" :key="block.id">
      <MessageBubble
        v-if="block.kind === 'msg'"
        :item="block.item"
        :model-provider="modelProvider"
        :model-name="modelName"
        @accept-plan="emit('accept-plan', $event)"
      />
      <ToolApprovalCard
        v-else-if="block.kind === 'approval'"
        :item="block.item"
        @resolve="onApproval(block.item, $event)"
      />
      <AskUserForm
        v-else-if="block.kind === 'ask'"
        :item="block.item"
        @submit="onAskSubmit(block.item, $event)"
        @dismiss="onAskDismiss(block.item)"
      />
      <PlanReviewCard
        v-else-if="block.kind === 'plan_review'"
        :item="block.item"
        :model-provider="modelProvider"
        :model-name="modelName"
        @resolve="onPlanReview(block.item, $event)"
      />
      <TodoListCard
        v-else-if="block.kind === 'todos'"
        :item="block.item"
      />
      <SubagentCard
        v-else-if="block.kind === 'subagent'"
        :item="block.item"
        @inspect="emit('inspect-tool', $event)"
      />
      <ToolCallGroup
        v-else-if="block.tools.length > 1"
        :tools="block.tools"
        @inspect="emit('inspect-tool', $event)"
      />
      <ToolCard
        v-else
        :item="block.tools[0]"
        @inspect="emit('inspect-tool', $event)"
      />
    </template>
  </div>
</template>

<style scoped>
.empty-ws {
  margin-top: 18px;
}
</style>
