// web/src/components/layout/RightDock.tsx
import { useCallback, useMemo, useRef, useState, type MouseEvent as ReactMouseEvent } from "react";
import { RefreshCw, X } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { HoverCard, HoverCardContent, HoverCardTrigger } from "@/components/ui/hover-card";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import type { DockPane, useRightDock } from "@/hooks/useRightDock";
import {
  estimateContextOccupancy,
  formatCompactTokens,
  formatSharePercent,
} from "@/lib/contextEstimate";
import { formatTokenCount } from "@/lib/pricing";
import { pretty } from "@/lib/pretty";
import type { Plugin, Tool, Usage } from "@/types/api";
import { cn } from "@/lib/utils";

export type ActivityItem = {
  id?: string;
  kind: string;
  name?: string;
  detail?: unknown;
  at?: number;
  callId?: string;
};

export type RightDockController = ReturnType<typeof useRightDock>;

export type RightDockProps = {
  dock: RightDockController;
  plugins?: Plugin[];
  tools?: Tool[];
  activity?: ActivityItem[];
  usage?: Usage;
  pluginError?: string | null;
  reloading?: boolean;
  highlightActivityId?: string | null;
  inspectorPayload?: unknown;
  /** Context composition inputs (same as composer meter). */
  contextItems?: any[];
  modelName?: string;
  cwd?: string;
  workspaceTitle?: string;
  draft?: string;
  onTogglePlugin?: (pluginId: string, enabled: boolean) => void | Promise<void>;
  onReload?: () => void | Promise<void>;
  onReloadOne?: (pluginId: string) => void | Promise<void>;
  onRetryPlugin?: (pluginId: string) => void | Promise<void>;
  onViewSchema?: (tool: Tool) => void;
  onSavePluginConfig?: (
    pluginId: string,
    values: Record<string, string>,
  ) => void | Promise<void>;
  className?: string;
};

function activeKind(pane: DockPane): string | null {
  const tab = pane.tabs.find((t) => t.id === pane.activeId);
  return tab?.kind || null;
}

function cacheHitRate(usage: Usage): string {
  const prompt = Number(usage.prompt_tokens || 0);
  const cached = Number(usage.cached_tokens || 0);
  if (prompt > 0 && cached > 0) return `${((cached / prompt) * 100).toFixed(1)}%`;
  return "0%";
}

export function RightDock({
  dock,
  plugins = [],
  tools = [],
  activity = [],
  usage = {},
  pluginError,
  reloading = false,
  highlightActivityId,
  inspectorPayload,
  contextItems = [],
  modelName = "",
  cwd = "",
  workspaceTitle = "",
  draft = "",
  onTogglePlugin,
  onReload,
  onReloadOne,
  onRetryPlugin,
  onViewSchema,
  className,
}: RightDockProps) {
  const [toggling, setToggling] = useState<Record<string, boolean>>({});
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [schemaTool, setSchemaTool] = useState<Tool | null>(null);
  const [dragging, setDragging] = useState(false);
  const panesHostRef = useRef<HTMLDivElement>(null);

  const panes = dock.visiblePanes;
  const state = dock.state;

  const showSchema = useCallback(
    (tool: Tool) => {
      setSchemaTool(tool);
      onViewSchema?.(tool);
    },
    [onViewSchema],
  );

  const onToggle = useCallback(
    (plugin: Plugin, enabled: boolean) => {
      const id = plugin.plugin_id;
      setToggling((m) => ({ ...m, [id]: true }));
      void Promise.resolve(onTogglePlugin?.(id, enabled)).finally(() => {
        setTimeout(() => {
          setToggling((m) => ({ ...m, [id]: false }));
        }, 400);
      });
    },
    [onTogglePlugin],
  );

  const startDrag = useCallback(
    (e: ReactMouseEvent) => {
      e.preventDefault();
      setDragging(true);
      const host = panesHostRef.current;
      const onMove = (ev: MouseEvent) => {
        if (!host) return;
        const rect = host.getBoundingClientRect();
        const y = (ev.clientY - rect.top) / rect.height;
        dock.setRatio(y || state.ratio);
      };
      const onUp = () => {
        setDragging(false);
        window.removeEventListener("mousemove", onMove);
        window.removeEventListener("mouseup", onUp);
      };
      window.addEventListener("mousemove", onMove);
      window.addEventListener("mouseup", onUp);
    },
    [dock, state.ratio],
  );

  const totalTokens = useMemo(() => {
    if (usage.total_tokens != null) return Number(usage.total_tokens);
    return Number(usage.prompt_tokens || 0) + Number(usage.completion_tokens || 0);
  }, [usage]);

  return (
    <aside
      className={cn(
        "nlm-rail relative flex h-full min-h-0 w-[var(--rail-w)] flex-col overflow-hidden border-l border-border bg-card/70 backdrop-blur-md",
        className,
      )}
      aria-label="扩展停靠栏"
    >
      <div className="flex shrink-0 items-center justify-between border-b border-border px-2.5 py-2">
        <span className="text-[10.5px] uppercase tracking-[0.06em] text-muted-foreground">
          Dock
        </span>
        <div className="flex gap-1">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            className="h-7 px-2 text-[11px]"
            title={state.split ? "合并面板" : "拆分检查器"}
            onClick={() =>
              state.split ? dock.disableSplit() : dock.enableSplit("inspector")
            }
          >
            {state.split ? "合并" : "拆分"}
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="sm"
            className="h-7 px-2"
            title="重载插件"
            disabled={reloading}
            onClick={() => void onReload?.()}
          >
            <RefreshCw className={cn("size-3.5", reloading && "animate-spin")} />
          </Button>
        </div>
      </div>

      <div
        ref={panesHostRef}
        className={cn("flex min-h-0 flex-1 flex-col overflow-hidden", state.split && "gap-0")}
      >
        {panes.map((pane, pi) => {
          const kind = activeKind(pane);
          return (
            <div
              key={pane.id}
              className="relative flex min-h-0 flex-1 flex-col overflow-hidden"
              style={
                state.split && pi === 0
                  ? { flex: `0 0 ${state.ratio * 100}%` }
                  : state.split
                    ? { flex: "1 1 auto" }
                    : undefined
              }
            >
              <div className="flex shrink-0 flex-wrap gap-0.5 border-b border-border px-2 pt-1.5">
                {pane.tabs.map((tab) => (
                  <button
                    key={tab.id}
                    type="button"
                    className={cn(
                      "rounded-t-md px-2 py-1.5 text-[10.5px] text-muted-foreground",
                      pane.activeId === tab.id &&
                        "bg-primary/15 text-foreground shadow-[inset_0_-2px_0_hsl(var(--primary))]",
                    )}
                    onClick={() => dock.focusTab(pane.id, tab.id)}
                  >
                    {tab.title}
                    {(pane.id === "aux" || tab.kind === "inspector") && (
                      <span
                        className="ml-1 opacity-60 hover:opacity-100"
                        onClick={(e) => {
                          e.stopPropagation();
                          dock.closeTab(pane.id, tab.id);
                        }}
                      >
                        ×
                      </span>
                    )}
                  </button>
                ))}
              </div>

              <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
                {kind === "plugins" && (
                  <PluginsPanel
                    plugins={plugins}
                    pluginError={pluginError}
                    expanded={expanded}
                    toggling={toggling}
                    onExpand={(id) =>
                      setExpanded((m) => ({ ...m, [id]: !m[id] }))
                    }
                    onToggle={onToggle}
                    onReloadOne={onReloadOne}
                    onRetryPlugin={onRetryPlugin}
                    onShowSchema={showSchema}
                  />
                )}
                {kind === "activity" && (
                  <ActivityPanel
                    activity={activity}
                    highlightActivityId={highlightActivityId}
                    onOpen={(item) => dock.openInspector(item)}
                  />
                )}
                {kind === "usage" && (
                  <UsagePanel
                    usage={usage}
                    totalTokens={totalTokens}
                    tools={tools}
                    contextItems={contextItems}
                    modelName={modelName}
                    cwd={cwd}
                    workspaceTitle={workspaceTitle}
                    draft={draft}
                    onShowSchema={showSchema}
                  />
                )}
                {kind === "inspector" && (
                  <InspectorPanel
                    payload={
                      inspectorPayload ??
                      pane.tabs.find((t) => t.id === pane.activeId)?.params ?? {
                        tip: "从 Trajectory 或活动点击一行",
                      }
                    }
                  />
                )}
              </div>

              {state.split && pi === 0 ? (
                <div
                  className={cn(
                    "h-1.5 shrink-0 cursor-row-resize border-y border-border bg-foreground/[0.04] hover:bg-primary/20",
                    dragging && "bg-primary/20",
                  )}
                  onMouseDown={startDrag}
                />
              ) : null}
            </div>
          );
        })}
      </div>

      {schemaTool ? (
        <div
          className="absolute inset-0 z-[5] flex items-end bg-black/45 p-2.5"
          onClick={() => setSchemaTool(null)}
        >
          <div
            className="max-h-[70%] w-full overflow-auto rounded-[10px] border border-border bg-card p-2.5"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-1.5 flex items-center justify-between">
              <strong className="text-xs">{schemaTool.name}</strong>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="h-7 px-2"
                onClick={() => setSchemaTool(null)}
              >
                <X className="size-3.5" />
                关闭
              </Button>
            </div>
            <pre className="m-0 whitespace-pre-wrap font-mono text-[10.5px]">
              {pretty(schemaTool.inputSchema || schemaTool.parameters || {})}
            </pre>
          </div>
        </div>
      ) : null}
    </aside>
  );
}

function PluginsPanel({
  plugins,
  pluginError,
  expanded,
  toggling,
  onExpand,
  onToggle,
  onReloadOne,
  onRetryPlugin,
  onShowSchema,
}: {
  plugins: Plugin[];
  pluginError?: string | null;
  expanded: Record<string, boolean>;
  toggling: Record<string, boolean>;
  onExpand: (id: string) => void;
  onToggle: (plugin: Plugin, enabled: boolean) => void;
  onReloadOne?: (pluginId: string) => void | Promise<void>;
  onRetryPlugin?: (pluginId: string) => void | Promise<void>;
  onShowSchema: (tool: Tool) => void;
}) {
  return (
    <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto overscroll-contain p-2.5">
      <p className="m-0 text-[10.5px] text-muted-foreground">
        启停写入 prefs；仅 ready 进入模型工具列表
      </p>
      {pluginError ? (
        <p className="m-0 text-[10.5px] text-destructive">{pluginError}</p>
      ) : null}
      {!pluginError && plugins.length === 0 ? (
        <p className="m-0 text-[10.5px] text-muted-foreground">暂无插件</p>
      ) : null}
      <div className="flex flex-col gap-1.5">
        {plugins.map((p) => {
          const open = !!expanded[p.plugin_id];
          return (
            <div
              key={p.plugin_id}
              className={cn(
                "rounded-lg border border-border bg-foreground/[0.03] px-2.5 py-2",
                p.state === "error" && "border-destructive/40",
              )}
            >
              <div className="flex items-start gap-2">
                <button
                  type="button"
                  className="min-w-0 flex-1 text-left"
                  onClick={() => onExpand(p.plugin_id)}
                >
                  <div className="flex items-center gap-1.5">
                    <span className="text-xs font-semibold">{p.name || p.plugin_id}</span>
                    <Badge
                      variant="outline"
                      className={cn(
                        "h-4 px-1 font-mono text-[10px] uppercase",
                        p.state === "ready" && "border-teal/40 text-teal",
                        p.state === "error" && "border-destructive/50 text-destructive",
                      )}
                    >
                      {p.state || "—"}
                    </Badge>
                  </div>
                  <div className="font-mono text-[10.5px] text-muted-foreground">
                    {p.plugin_id} · {p.kind}
                  </div>
                </button>
                <div className="flex items-center gap-1">
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="size-7"
                    onClick={() => void onReloadOne?.(p.plugin_id)}
                  >
                    <RefreshCw className="size-3" />
                  </Button>
                  <Switch
                    checked={!!p.enabled}
                    disabled={!!toggling[p.plugin_id]}
                    onCheckedChange={(v) => onToggle(p, v)}
                  />
                </div>
              </div>
              {p.last_error && p.state === "error" ? (
                <div className="mt-1.5 text-[10.5px] text-destructive">{p.last_error}</div>
              ) : null}
              {p.state === "error" ? (
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="mt-1 h-7 px-2 text-[11px]"
                  onClick={() => void onRetryPlugin?.(p.plugin_id)}
                >
                  重试启用
                </Button>
              ) : null}
              {(p.config_hints || []).map((h, i) => (
                <div key={i} className="mt-1 text-[10.5px] text-[hsl(var(--tool))]">
                  {h}
                </div>
              ))}
              {open ? (
                <div className="mt-2 flex flex-wrap gap-1">
                  {(p.tools || []).length ? (
                    (p.tools || []).map((t) => (
                      <button
                        key={t.name}
                        type="button"
                        onClick={() => onShowSchema(t)}
                      >
                        <Badge
                          variant="outline"
                          className={cn(
                            "font-mono text-[10px]",
                            p.state === "ready" && "border-teal/35 text-teal",
                          )}
                        >
                          {t.name}
                        </Badge>
                      </button>
                    ))
                  ) : (
                    <Badge variant="outline" className="text-[10px]">
                      {p.enabled ? "no tools" : "已禁用"}
                    </Badge>
                  )}
                </div>
              ) : null}
            </div>
          );
        })}
      </div>
    </div>
  );
}

function ActivityPanel({
  activity,
  highlightActivityId,
  onOpen,
}: {
  activity: ActivityItem[];
  highlightActivityId?: string | null;
  onOpen: (item: ActivityItem) => void;
}) {
  return (
    <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto overscroll-contain p-2.5">
      <p className="m-0 text-[10.5px] text-muted-foreground">本会话工具活动</p>
      {!activity.length ? (
        <p className="m-0 text-[10.5px] text-muted-foreground">暂无工具活动</p>
      ) : (
        <div className="flex flex-col gap-1.5">
          {activity.map((item) => (
            <button
              key={item.id || item.at}
              type="button"
              className={cn(
                "rounded-lg border border-[hsl(var(--tool)/0.22)] bg-[hsl(var(--tool)/0.06)] px-2 py-1.5 text-left text-[10.5px]",
                item.id &&
                  item.id === highlightActivityId &&
                  "outline outline-1 outline-primary/55 bg-primary/15",
              )}
              onClick={() => onOpen(item)}
            >
              <span className="mr-1.5 font-mono text-[hsl(var(--tool))]">{item.kind}</span>
              <span className="font-mono">{item.name}</span>
              <pre className="mt-1 max-h-[90px] overflow-auto whitespace-pre-wrap break-words text-muted-foreground">
                {pretty(item.detail)}
              </pre>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function UsagePanel({
  usage,
  totalTokens,
  tools,
  contextItems = [],
  modelName = "",
  cwd = "",
  workspaceTitle = "",
  draft = "",
  onShowSchema,
}: {
  usage: Usage;
  totalTokens: number;
  tools: Tool[];
  contextItems?: any[];
  modelName?: string;
  cwd?: string;
  workspaceTitle?: string;
  draft?: string;
  onShowSchema: (tool: Tool) => void;
}) {
  const lastPromptTokens = useMemo(() => {
    for (let i = contextItems.length - 1; i >= 0; i -= 1) {
      const it = contextItems[i];
      if (it?.kind === "msg" && it.role === "assistant" && it.usage?.prompt_tokens) {
        return Number(it.usage.prompt_tokens) || 0;
      }
    }
    return 0;
  }, [contextItems]);

  const occupancy = useMemo(
    () =>
      estimateContextOccupancy({
        items: contextItems,
        tools,
        modelName,
        cwd,
        workspaceTitle,
        lastPromptTokens,
        draft,
      }),
    [contextItems, tools, modelName, cwd, workspaceTitle, lastPromptTokens, draft],
  );

  const compositionRows = useMemo(() => {
    const b = occupancy.breakdown;
    return [
      {
        key: "system" as const,
        label: "系统提示",
        tokens: b.systemTokens,
        share: occupancy.windowShares.system,
        usedShare: occupancy.usedShares.system,
        color: "bg-[#7aa2c8]",
      },
      {
        key: "tools" as const,
        label: "工具定义",
        tokens: b.toolsTokens,
        share: occupancy.windowShares.tools,
        usedShare: occupancy.usedShares.tools,
        color: "bg-[#a78bfa]",
      },
      {
        key: "messages" as const,
        label: "对话消息",
        tokens: b.messageTokens,
        share: occupancy.windowShares.messages,
        usedShare: occupancy.usedShares.messages,
        color: "bg-[#3a9cf0]",
      },
      {
        key: "free" as const,
        label: "剩余可用",
        tokens: b.freeTokens,
        share: occupancy.windowShares.free,
        usedShare: 0,
        color: "bg-foreground/15",
      },
    ];
  }, [occupancy]);

  const prompt = Number(usage.prompt_tokens || 0);
  const completion = Number(usage.completion_tokens || 0);
  const cached = Number(usage.cached_tokens || 0);
  const ioTotal = Math.max(1, prompt + completion);
  const ioRows = [
    {
      key: "prompt",
      label: "输入",
      value: prompt,
      width: (prompt / ioTotal) * 100,
      color: "bg-[#3a9cf0]",
    },
    {
      key: "completion",
      label: "输出",
      value: completion,
      width: (completion / ioTotal) * 100,
      color: "bg-[#2bb8a0]",
    },
  ];
  const cacheShare = prompt > 0 ? cached / prompt : 0;

  return (
    <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto overscroll-contain p-2.5">
      <div className="mb-1 rounded-lg border border-border bg-foreground/[0.03] p-2.5">
        <div className="mb-2 flex items-center justify-between gap-2 text-[10.5px] uppercase tracking-wide text-muted-foreground">
          <span>上下文构成</span>
          <span className="normal-case tracking-normal font-mono text-foreground">
            {occupancy.percent}% · ~{formatCompactTokens(occupancy.usedTokens)} /{" "}
            {formatCompactTokens(occupancy.contextWindow)}
          </span>
        </div>
        <div className="mb-2 flex h-2 overflow-hidden rounded-full bg-muted" aria-hidden>
          {compositionRows
            .filter((r) => r.key !== "free" && r.tokens > 0)
            .map((row) => (
              <div
                key={row.key}
                className={cn("h-full min-w-[2px]", row.color)}
                style={{
                  width: `${Math.max(occupancy.percent * row.usedShare, 0.4)}%`,
                }}
                title={row.label}
              />
            ))}
        </div>
        <div className="space-y-1">
          {compositionRows.map((row) => (
            <div key={row.key} className="flex items-center justify-between gap-2 text-xs">
              <span className="inline-flex min-w-0 items-center gap-1.5 text-muted-foreground">
                <span className={cn("size-2 shrink-0 rounded-sm", row.color)} aria-hidden />
                <span className="truncate">{row.label}</span>
              </span>
              <span className="shrink-0 tabular-nums">
                <span className="mr-2 text-muted-foreground">{formatSharePercent(row.share)}</span>
                <strong className="font-mono font-medium text-foreground">
                  ~{formatCompactTokens(row.tokens)}
                </strong>
              </span>
            </div>
          ))}
        </div>
      </div>

      <div className="mb-1 rounded-lg border border-border bg-foreground/[0.03] p-2.5">
        <div className="mb-2 flex items-center justify-between gap-2 text-[10.5px] uppercase tracking-wide text-muted-foreground">
          <span>会话累计</span>
          <HoverCard>
            <HoverCardTrigger asChild>
              <button type="button" className="normal-case tracking-normal text-primary/80 hover:underline">
                详情
              </button>
            </HoverCardTrigger>
            <HoverCardContent className="w-56 text-xs">
              <p className="m-0 font-medium text-foreground">Token 分布</p>
              <p className="mt-1 m-0 text-muted-foreground">
                输入 {formatTokenCount(prompt)} · 输出 {formatTokenCount(completion)} · 缓存{" "}
                {formatTokenCount(cached)}
              </p>
            </HoverCardContent>
          </HoverCard>
        </div>

        <div className="mb-1.5 flex justify-between text-[10.5px] text-muted-foreground">
          <span>输入 / 输出占比</span>
          <span className="font-mono">{formatTokenCount(totalTokens)}</span>
        </div>
        <div className="mb-2 flex h-2 overflow-hidden rounded-full bg-muted" aria-hidden>
          {ioRows
            .filter((r) => r.value > 0)
            .map((row) => (
              <div
                key={row.key}
                className={cn("h-full min-w-[2px]", row.color)}
                style={{ width: `${Math.max(row.width, 0.5)}%` }}
                title={`${row.label} ${row.value}`}
              />
            ))}
        </div>
        {ioRows.map((row) => (
          <div key={row.key} className="flex items-center justify-between gap-2 py-0.5 text-xs">
            <span className="inline-flex items-center gap-1.5 text-muted-foreground">
              <span className={cn("size-2 rounded-sm", row.color)} aria-hidden />
              {row.label}
            </span>
            <span className="tabular-nums">
              <span className="mr-2 text-muted-foreground">
                {formatSharePercent(row.value / ioTotal)}
              </span>
              <strong className="font-mono font-medium">{formatTokenCount(row.value)}</strong>
            </span>
          </div>
        ))}
        <UsageRow label="合计" value={formatTokenCount(totalTokens)} />
        <div className="mt-1.5 flex items-center justify-between gap-2 py-0.5 text-xs">
          <span className="text-muted-foreground">缓存命中</span>
          <span className="tabular-nums">
            <span className="mr-2 text-muted-foreground">{formatSharePercent(cacheShare)}</span>
            <strong className="font-mono font-medium">{formatTokenCount(cached)}</strong>
          </span>
        </div>
        <div className="mt-1.5">
          <div className="mb-1 flex justify-between text-[10.5px] text-muted-foreground">
            <span>缓存命中率</span>
            <span className="font-mono">{cacheHitRate(usage)}</span>
          </div>
          <Progress value={Math.min(100, cacheShare * 100)} />
        </div>
        <p className="mt-2 text-[10.5px] text-muted-foreground">
          {usage.estimated
            ? "含估算值（接口未返回 usage 时按约 4 字/token）。"
            : "优先使用接口返回的 usage；上下文构成为启发式估算。"}
        </p>
      </div>
      <p className="m-0 text-[10.5px] text-muted-foreground">已启用工具 · {tools.length}</p>
      <div className="flex flex-col gap-1.5">
        {tools.map((t) => (
          <button
            key={`${t.openai_name || t.name}-${t.plugin_id || ""}`}
            type="button"
            className="flex w-full flex-col gap-0.5 rounded-md border border-border bg-foreground/[0.02] px-2 py-1.5 text-left text-[10.5px] hover:border-primary/35"
            onClick={() => onShowSchema(t)}
          >
            <div className="flex justify-between gap-2">
              <span className="font-mono">{t.name}</span>
              <span className="text-muted-foreground">{t.plugin_id}</span>
            </div>
            {t.description ? (
              <div className="text-muted-foreground">{t.description}</div>
            ) : null}
          </button>
        ))}
        {!tools.length ? (
          <p className="m-0 text-[10.5px] text-muted-foreground">当前无已启用工具</p>
        ) : null}
      </div>
    </div>
  );
}

function UsageRow({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="flex justify-between py-0.5 text-xs">
      <span className="text-muted-foreground">{label}</span>
      <strong className="font-mono font-medium">{value}</strong>
    </div>
  );
}

function InspectorPanel({ payload }: { payload: unknown }) {
  return (
    <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto overscroll-contain p-2.5">
      <p className="m-0 text-[10.5px] text-muted-foreground">
        检查器 · Trajectory / 活动详情
      </p>
      <pre className="m-0 max-h-full overflow-auto whitespace-pre-wrap break-words rounded-lg border border-border bg-background/60 p-2 font-mono text-[10.5px]">
        {pretty(payload)}
      </pre>
    </div>
  );
}

export default RightDock;

// web/src/components/RightDock.vue
<script setup>
import { pretty } from "@/utils/pretty";
import { computed, ref } from "vue";

const props = defineProps({
  dock: { type: Object, required: true },
  plugins: { type: Array, default: () => [] },
  tools: { type: Array, default: () => [] },
  activity: { type: Array, default: () => [] },
  usage: { type: Object, default: () => ({}) },
  pluginError: String,
  reloading: Boolean,
  highlightActivityId: String,
  inspectorPayload: { type: Object, default: null },
});

const emit = defineEmits([
  "toggle-plugin",
  "reload",
  "reload-one",
  "retry-plugin",
  "view-schema",
]);

const schemaTool = ref(null);
const expanded = ref({});
const toggling = ref({});
const dragging = ref(false);

const state = computed(() => props.dock.state);
const panes = computed(() => {
  const raw = props.dock.visiblePanes;
  if (Array.isArray(raw)) return raw;
  if (raw && Array.isArray(raw.value)) return raw.value;
  return props.dock.state?.panes?.[0] ? [props.dock.state.panes[0]] : [];
});

function paneTabs(pane) {
  return pane.tabs || [];
}

function activeKind(pane) {
  const tab = pane.tabs.find((t) => t.id === pane.activeId);
  return tab?.kind || null;
}

function onToggle(plugin, enabled) {
  toggling.value[plugin.plugin_id] = true;
  emit("toggle-plugin", plugin.plugin_id, enabled);
  setTimeout(() => {
    toggling.value[plugin.plugin_id] = false;
  }, 500);
}

function showSchema(tool) {
  schemaTool.value = tool;
  emit("view-schema", tool);
}

function closeSchema() {
  schemaTool.value = null;
}

function isHighlighted(item) {
  return item.id && item.id === props.highlightActivityId;
}

function startDrag(e) {
  dragging.value = true;
  const startY = e.clientY;
  const startRatio = state.value.ratio;
  const host = e.currentTarget.parentElement;
  function onMove(ev) {
    if (!host) return;
    const rect = host.getBoundingClientRect();
    const y = (ev.clientY - rect.top) / rect.height;
    props.dock.setRatio(y || startRatio);
  }
  function onUp() {
    dragging.value = false;
    window.removeEventListener("mousemove", onMove);
    window.removeEventListener("mouseup", onUp);
  }
  window.addEventListener("mousemove", onMove);
  window.addEventListener("mouseup", onUp);
}
</script>

<template>
  <aside class="rail dock" aria-label="扩展停靠栏">
    <div class="dock-toolbar">
      <span class="dock-title">Dock</span>
      <div class="dock-actions">
        <NlmButton
          variant="ghost"
          :title="state.split ? '合并面板' : '拆分检查器'"
          @click="state.split ? dock.disableSplit() : dock.enableSplit('inspector')"
        >
          {{ state.split ? "合并" : "拆分" }}
        </NlmButton>
        <NlmButton variant="ghost" title="重载插件" :disabled="reloading" @click="emit('reload')">
          {{ reloading ? "…" : "↻" }}
        </NlmButton>
      </div>
    </div>

    <div class="dock-panes" :class="{ split: state.split }">
      <div
        v-for="(pane, pi) in panes"
        :key="pane.id"
        class="dock-pane"
        :style="
          state.split && pi === 0
            ? { flex: `0 0 ${state.ratio * 100}%` }
            : state.split
              ? { flex: '1 1 auto' }
              : {}
        "
      >
        <div class="dock-tabs">
          <button
            v-for="tab in paneTabs(pane)"
            :key="tab.id"
            type="button"
            class="dock-tab"
            :class="{ active: pane.activeId === tab.id }"
            @click="dock.focusTab(pane.id, tab.id)"
          >
            {{ tab.title }}
            <span
              v-if="pane.id === 'aux' || tab.kind === 'inspector'"
              class="tab-x"
              @click.stop="dock.closeTab(pane.id, tab.id)"
            >×</span>
          </button>
        </div>

        <div class="dock-body">
          <!-- plugins -->
          <div v-show="activeKind(pane) === 'plugins'" class="rail-panel active">
            <div class="rail-hint">启停写入 prefs；仅 ready 进入模型工具列表</div>
            <div class="plugin-list">
              <div v-if="pluginError" class="rail-hint">{{ pluginError }}</div>
              <div v-else-if="!plugins.length" class="rail-hint">暂无插件</div>
              <div
                v-for="p in plugins"
                :key="p.plugin_id"
                class="plugin-card"
                :class="{ 'is-error': p.state === 'error' }"
              >
                <div class="plugin-card-head">
                  <button type="button" class="meta-btn" @click="expanded[p.plugin_id] = !expanded[p.plugin_id]">
                    <div class="meta">
                      <div class="name-row">
                        <span class="name">{{ p.name || p.plugin_id }}</span>
                        <span class="state-badge" :class="'st-' + p.state">{{ p.state }}</span>
                      </div>
                      <div class="id">{{ p.plugin_id }} · {{ p.kind }}</div>
                    </div>
                  </button>
                  <div class="plugin-actions">
                    <NlmButton variant="ghost" @click="emit('reload-one', p.plugin_id)">↻</NlmButton>
                    <NlmSwitch
                      :model-value="!!p.enabled"
                      :disabled="!!toggling[p.plugin_id]"
                      @change="(v) => onToggle(p, v)"
                    />
                  </div>
                </div>
                <div v-if="p.last_error && p.state === 'error'" class="err">{{ p.last_error }}</div>
                <div v-if="p.state === 'error'" class="retry-row">
                  <NlmButton variant="ghost" @click="emit('retry-plugin', p.plugin_id)">重试启用</NlmButton>
                </div>
                <div v-if="(p.config_hints || []).length" class="hints">
                  <div v-for="(h, i) in p.config_hints" :key="i" class="hint">{{ h }}</div>
                </div>
                <div v-if="expanded[p.plugin_id]" class="tools">
                  <button
                    v-for="t in p.tools || []"
                    :key="t.name"
                    type="button"
                    class="tool-chip-btn"
                    @click="showSchema(t)"
                  >
                    <NlmChip :active="p.state === 'ready'">{{ t.name }}</NlmChip>
                  </button>
                </div>
              </div>
            </div>
          </div>

          <!-- activity -->
          <div v-show="activeKind(pane) === 'activity'" class="rail-panel active">
            <div class="rail-hint">本会话工具活动</div>
            <div class="activity-list">
              <div v-if="!activity.length" class="rail-hint">暂无工具活动</div>
              <div
                v-for="item in activity"
                :key="item.id || item.at"
                class="activity-item"
                :class="{ highlight: isHighlighted(item) }"
                @click="dock.openInspector(item)"
              >
                <span class="kind">{{ item.kind }}</span>
                <span class="name">{{ item.name }}</span>
                <pre>{{ pretty(item.detail) }}</pre>
              </div>
            </div>
          </div>

          <!-- usage -->
          <div v-show="activeKind(pane) === 'usage'" class="rail-panel active">
            <div class="usage-card">
              <div class="usage-label">会话累计</div>
              <div class="usage-row"><span>输入</span><strong>{{ Number(usage.prompt_tokens || 0) }}</strong></div>
              <div class="usage-row"><span>输出</span><strong>{{ Number(usage.completion_tokens || 0) }}</strong></div>
              <div class="usage-row">
                <span>合计</span>
                <strong>{{ Number(usage.total_tokens || (usage.prompt_tokens || 0) + (usage.completion_tokens || 0)) }}</strong>
              </div>
              <div class="usage-row">
                <span>缓存命中</span>
                <strong>{{ Number(usage.cached_tokens || 0) }}</strong>
              </div>
              <div class="usage-row">
                <span>命中率</span>
                <strong>
                  {{
                    Number(usage.prompt_tokens || 0) > 0 && Number(usage.cached_tokens || 0) > 0
                      ? ((Number(usage.cached_tokens) / Number(usage.prompt_tokens)) * 100).toFixed(1) + "%"
                      : "0%"
                  }}
                </strong>
              </div>
              <p class="rail-hint">
                {{
                  usage.estimated
                    ? "含估算值（接口未返回 usage 时按约 4 字/token）。"
                    : "优先使用接口返回的 usage；费用估算见输入栏。"
                }}
              </p>
            </div>
            <div class="rail-hint">已启用工具</div>
            <div class="tool-list">
              <button
                v-for="t in tools"
                :key="(t.openai_name || t.name) + (t.plugin_id || '')"
                type="button"
                class="tool-row rich"
                @click="showSchema(t)"
              >
                <div class="tmain">
                  <span class="tname">{{ t.name }}</span>
                  <span class="pid">{{ t.plugin_id }}</span>
                </div>
                <div v-if="t.description" class="tdesc">{{ t.description }}</div>
              </button>
              <div v-if="!tools.length" class="rail-hint">当前无已启用工具</div>
            </div>
          </div>

          <!-- inspector -->
          <div v-show="activeKind(pane) === 'inspector'" class="rail-panel active">
            <div class="rail-hint">检查器 · Trajectory / 活动详情</div>
            <pre class="inspector-pre">{{ pretty(inspectorPayload || pane.tabs.find((t) => t.id === pane.activeId)?.params || { tip: "从 Trajectory 或活动点击一行" }) }}</pre>
          </div>
        </div>

        <div
          v-if="state.split && pi === 0"
          class="dock-splitter"
          :class="{ dragging }"
          @mousedown.prevent="startDrag"
        />
      </div>
    </div>

    <div v-if="schemaTool" class="schema-modal" @click.self="closeSchema">
      <div class="schema-card">
        <div class="schema-head">
          <strong>{{ schemaTool.name }}</strong>
          <NlmButton variant="ghost" @click="closeSchema">关闭</NlmButton>
        </div>
        <pre>{{ pretty(schemaTool.inputSchema || schemaTool.parameters || {}) }}</pre>
      </div>
    </div>
  </aside>
</template>

<style scoped>
.dock {
  position: relative;
  display: flex;
  flex-direction: column;
  min-height: 0;
  height: 100%;
  overflow: hidden;
}
.dock-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 10px;
  border-bottom: 1px solid var(--line);
  flex-shrink: 0;
}
.dock-title {
  font-size: var(--fs-xs);
  color: var(--muted);
  letter-spacing: 0.06em;
  text-transform: uppercase;
}
.dock-actions {
  display: flex;
  gap: 4px;
}
.dock-panes {
  flex: 1;
  min-height: 0;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.dock-pane {
  flex: 1;
  min-height: 0;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  position: relative;
}
.dock-panes.split .dock-pane {
  min-height: 0;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  position: relative;
}
.dock-tabs {
  display: flex;
  flex-wrap: wrap;
  gap: 2px;
  padding: 6px 8px 0;
  border-bottom: 1px solid var(--line);
  flex-shrink: 0;
}
.dock-tab {
  border: 0;
  background: transparent;
  color: var(--muted);
  font: inherit;
  font-size: var(--fs-xs);
  padding: 6px 8px;
  border-radius: 7px 7px 0 0;
  cursor: pointer;
}
.dock-tab.active {
  color: var(--ink);
  background: rgba(58, 156, 240, 0.12);
  box-shadow: inset 0 -2px 0 var(--accent);
}
.tab-x {
  margin-left: 4px;
  opacity: 0.6;
}
.dock-body {
  flex: 1;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  min-height: 0;
}
.rail-panel.active {
  display: flex;
  flex: 1;
  overflow-y: auto;
  overscroll-behavior: contain;
  padding: 10px;
  flex-direction: column;
  gap: 8px;
  min-height: 0;
}
.dock-splitter {
  height: 5px;
  cursor: row-resize;
  background: rgba(255, 255, 255, 0.04);
  border-top: 1px solid var(--line);
  border-bottom: 1px solid var(--line);
  flex-shrink: 0;
}
.dock-splitter.dragging,
.dock-splitter:hover {
  background: rgba(58, 156, 240, 0.2);
}
.meta-btn {
  flex: 1;
  border: 0;
  background: transparent;
  color: inherit;
  text-align: left;
  padding: 0;
  cursor: pointer;
  font: inherit;
  min-width: 0;
}
.name-row {
  display: flex;
  gap: 6px;
  align-items: center;
}
.state-badge {
  font-family: var(--mono);
  font-size: 10px;
  padding: 1px 5px;
  border-radius: 4px;
  border: 1px solid var(--line);
  color: var(--muted);
  text-transform: uppercase;
}
.state-badge.st-ready {
  color: var(--teal);
  border-color: rgba(43, 184, 160, 0.4);
}
.state-badge.st-error {
  color: var(--danger);
}
.plugin-actions {
  display: flex;
  align-items: center;
  gap: 4px;
}
.err {
  color: var(--danger);
  font-size: var(--fs-xs);
  margin-top: 6px;
}
.hints .hint {
  font-size: var(--fs-xs);
  color: #c9a227;
}
.tool-chip-btn {
  border: 0;
  background: transparent;
  padding: 0;
  cursor: pointer;
}
.activity-item {
  cursor: pointer;
}
.activity-item.highlight {
  outline: 1px solid rgba(58, 156, 240, 0.55);
  background: rgba(58, 156, 240, 0.12);
}
.tool-row.rich {
  display: flex;
  flex-direction: column;
  width: 100%;
  text-align: left;
  cursor: pointer;
  background: rgba(255, 255, 255, 0.02);
  color: inherit;
  font: inherit;
}
.tmain {
  display: flex;
  justify-content: space-between;
  gap: 8px;
}
.tdesc {
  color: var(--muted);
  font-size: var(--fs-xs);
}
.inspector-pre {
  margin: 0;
  padding: 8px;
  border-radius: 8px;
  background: rgba(0, 0, 0, 0.28);
  border: 1px solid var(--line);
  font-family: var(--mono);
  font-size: var(--fs-xs);
  white-space: pre-wrap;
  word-break: break-word;
  max-height: 100%;
  overflow: auto;
}
.schema-modal {
  position: absolute;
  inset: 0;
  background: rgba(0, 0, 0, 0.45);
  display: flex;
  align-items: flex-end;
  padding: 10px;
  z-index: 5;
}
.schema-card {
  width: 100%;
  max-height: 70%;
  overflow: auto;
  background: var(--panel-solid);
  border: 1px solid var(--line);
  border-radius: 10px;
  padding: 10px;
}
.schema-head {
  display: flex;
  justify-content: space-between;
  margin-bottom: 6px;
}
.schema-card pre {
  margin: 0;
  font-family: var(--mono);
  font-size: var(--fs-xs);
  white-space: pre-wrap;
}
</style>
