// web/src/components/layout/Sidebar.tsx
import { Plus, Settings, X } from "lucide-react";

import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import type { LocalConversation } from "@/hooks/useSessions";
import type { Workspace } from "@/types/api";
import { cn } from "@/lib/utils";

export type SidebarConversation = Pick<
  LocalConversation,
  "id" | "title" | "preview" | "cwd" | "workspaceTitle"
> &
  Partial<Pick<LocalConversation, "updatedAt" | "workspaceId" | "workspaceKind" | "sshHostId">>;

export type SidebarWorkspace = Pick<Workspace, "id" | "path"> &
  Partial<Pick<Workspace, "title" | "kind" | "ssh_host_id">>;

export type SidebarProps = {
  conversations?: SidebarConversation[];
  workspaces?: SidebarWorkspace[];
  activeId?: string | null;
  status?: string;
  onNew?: () => void;
  onSelect?: (id: string) => void;
  onDelete?: (id: string) => void;
  onOpenWorkspace?: (workspace: SidebarWorkspace) => void;
  onOpenSettings?: () => void;
  className?: string;
};

export function Sidebar({
  conversations = [],
  workspaces = [],
  activeId,
  status = "ready",
  onNew,
  onSelect,
  onDelete,
  onOpenWorkspace,
  onOpenSettings,
  className,
}: SidebarProps) {
  return (
    <aside
      className={cn(
        "nlm-sidebar flex h-full min-h-0 flex-col gap-2.5 overflow-hidden border-r border-border bg-[var(--sidebar-bg)] px-3 py-3.5 backdrop-blur-md",
        className,
      )}
    >
      <div className="shrink-0">
        <div className="bg-gradient-to-br from-foreground via-primary to-teal bg-clip-text text-[15px] font-bold tracking-tight text-transparent">
          Nexus Lark Mind
        </div>
        <p className="m-0 mt-0.5 text-[10.5px] uppercase tracking-[0.06em] text-muted-foreground">
          Agent Console
        </p>
      </div>

      <Button
        type="button"
        className="h-8 w-full justify-start gap-1.5 border border-primary/35 bg-primary/15 text-foreground hover:bg-primary/25"
        variant="secondary"
        size="sm"
        onClick={onNew}
      >
        <Plus className="size-3.5" />
        新对话
      </Button>

      <div className="mt-1 shrink-0 text-[10.5px] tracking-wide text-muted-foreground">
        工作目录
      </div>
      <div className="flex max-h-[120px] shrink-0 flex-col gap-1 overflow-auto overscroll-contain px-0.5">
        {workspaces.length === 0 ? (
          <div className="px-0.5 py-1 text-[11px] text-muted-foreground">
            在空对话中添加 Workspace
          </div>
        ) : (
          workspaces.map((w) => (
            <button
              key={w.id}
              type="button"
              title={w.path}
              className="rounded-lg border border-border bg-foreground/[0.03] px-2 py-1.5 text-left transition-colors hover:border-primary/40"
              onClick={() => onOpenWorkspace?.(w)}
            >
              <span className="block truncate text-xs">{w.title || w.path}</span>
            </button>
          ))
        )}
      </div>

      <div className="mt-1 shrink-0 text-[10.5px] tracking-wide text-muted-foreground">
        历史记录
      </div>
      <ScrollArea className="min-h-0 flex-1">
        <div className="flex flex-col gap-1 pr-1">
          {conversations.length === 0 ? (
            <div className="px-2 py-2 text-[11px] text-muted-foreground">暂无历史</div>
          ) : (
            conversations.map((c) => {
              const active = c.id === activeId;
              const preview = c.cwd ? c.workspaceTitle || c.cwd : c.preview || "";
              return (
                <button
                  key={c.id}
                  type="button"
                  className={cn(
                    "group grid w-full grid-cols-[1fr_auto] gap-x-1.5 gap-y-1 rounded-lg border border-transparent px-2.5 py-2 text-left transition-colors",
                    "hover:bg-foreground/[0.04]",
                    active && "border-primary/30 bg-primary/15",
                  )}
                  onClick={() => onSelect?.(c.id)}
                >
                  <span className="truncate text-xs font-medium">{c.title || "新对话"}</span>
                  <span
                    role="button"
                    tabIndex={0}
                    title="删除"
                    className="opacity-0 transition-opacity group-hover:opacity-100"
                    onClick={(e) => {
                      e.stopPropagation();
                      onDelete?.(c.id);
                    }}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" || e.key === " ") {
                        e.preventDefault();
                        e.stopPropagation();
                        onDelete?.(c.id);
                      }
                    }}
                  >
                    <X className="size-3.5 text-muted-foreground hover:text-destructive" />
                  </span>
                  {preview ? (
                    <span className="col-span-2 truncate text-[10.5px] text-muted-foreground">
                      {preview}
                    </span>
                  ) : null}
                </button>
              );
            })
          )}
        </div>
      </ScrollArea>

      <div className="flex shrink-0 items-center justify-between gap-2 border-t border-border pt-2 text-[10.5px] text-muted-foreground">
        <button
          type="button"
          className="inline-flex items-center gap-1 hover:text-foreground"
          onClick={onOpenSettings}
        >
          <Settings className="size-3" />
          设置
        </button>
        <span className="truncate font-mono">{status}</span>
      </div>
    </aside>
  );
}

export default Sidebar;

// web/src/components/Sidebar.vue
<script setup>
defineProps({
  conversations: { type: Array, default: () => [] },
  workspaces: { type: Array, default: () => [] },
  activeId: String,
  status: { type: String, default: "ready" },
});
const emit = defineEmits(["new", "select", "delete", "open-settings", "open-workspace"]);
</script>

<template>
  <aside class="sidebar">
    <div class="sidebar-brand">
      <div class="logo">Nexus Lark Mind</div>
      <p class="brand-sub">Agent Console</p>
    </div>
    <NlmButton variant="new" block @click="emit('new')">＋ 新对话</NlmButton>

    <div class="sidebar-label">工作目录</div>
    <div class="ws-side-list">
      <button
        v-for="w in workspaces"
        :key="w.id"
        type="button"
        class="ws-side-item"
        :title="w.path"
        @click="emit('open-workspace', w)"
      >
        <span class="ws-title">{{ w.title }}</span>
      </button>
      <div v-if="!workspaces.length" class="ws-empty">在空对话中添加 Workspace</div>
    </div>

    <div class="sidebar-label">历史记录</div>
    <div class="conv-list">
      <div v-if="!conversations.length" style="color: var(--muted); font-size: 11px; padding: 8px">
        暂无历史
      </div>
      <button
        v-for="c in conversations"
        :key="c.id"
        type="button"
        class="conv-item"
        :class="{ active: c.id === activeId }"
        @click="emit('select', c.id)"
      >
        <span class="title">{{ c.title || "新对话" }}</span>
        <span class="del" title="删除" @click.stop="emit('delete', c.id)">×</span>
        <span class="preview">{{ c.cwd ? c.workspaceTitle || c.cwd : c.preview || "" }}</span>
      </button>
    </div>
    <div class="sidebar-foot">
      <button type="button" class="settings-link" @click="emit('open-settings')">⚙ 设置</button>
      <span>{{ status }}</span>
    </div>
  </aside>
</template>

<style scoped>
.ws-side-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 0 10px 10px;
  max-height: 120px;
  overflow: auto;
  overscroll-behavior: contain;
  flex-shrink: 0;
}
.ws-side-item {
  text-align: left;
  border: 1px solid var(--line);
  background: rgba(255, 255, 255, 0.03);
  color: var(--ink);
  border-radius: 8px;
  padding: 6px 8px;
  font: inherit;
  cursor: pointer;
}
.ws-side-item:hover {
  border-color: rgba(58, 156, 240, 0.4);
}
.ws-title {
  font-size: 12px;
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.ws-empty {
  color: var(--muted);
  font-size: 11px;
  padding: 4px 2px;
}
</style>
