// web/src/components/chat/SubagentCard.tsx
import { useMemo, useState } from "react";
import { ChevronRight } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { Progress } from "@/components/ui/progress";
import { pretty } from "@/lib/pretty";
import { cn } from "@/lib/utils";

export type SubagentChildTool = {
  id?: string;
  name?: string;
  success?: boolean | null;
  status?: string;
};

export type SubagentItem = {
  open?: boolean;
  error?: unknown;
  status?: string;
  output?: string;
  label?: string;
  name?: string;
  mode?: string;
  subagentId?: string;
  prompt?: string;
  streamText?: string;
  childTools?: SubagentChildTool[];
  activityId?: string;
};

export type SubagentCardProps = {
  item: SubagentItem;
  onInspect?: (activityId: string) => void;
  onOpenChange?: (open: boolean) => void;
  className?: string;
};

export function SubagentCard({ item, onInspect, onOpenChange, className }: SubagentCardProps) {
  const [open, setOpen] = useState(!!item.open);

  const statusLabel = useMemo(() => {
    if (item.error) return "失败";
    if (item.status === "running") return "运行中";
    if (item.status === "interrupted") return "已中断";
    if (item.status === "idle" || item.output) return "完成";
    return item.status || "subagent";
  }, [item.error, item.status, item.output]);

  const summary = useMemo(() => {
    return [item.label || item.name || "subagent", item.mode ? String(item.mode) : null, statusLabel]
      .filter(Boolean)
      .join(" · ");
  }, [item.label, item.name, item.mode, statusLabel]);

  const nestedTools = item.childTools || [];
  const tone =
    item.status || (item.error ? "fail" : item.output ? "ok" : "running");

  return (
    <Collapsible
      open={open}
      onOpenChange={(next) => {
        setOpen(next);
        item.open = next;
        onOpenChange?.(next);
      }}
      className={cn(
        "subagent-card w-fit max-w-[min(100%,560px)] self-start animate-in fade-in duration-150",
        open && "w-[min(100%,560px)] rounded-lg border border-violet-400/35 bg-violet-400/10",
        className,
      )}
    >
      <CollapsibleTrigger asChild>
        <button
          type="button"
          className={cn(
            "inline-flex items-center gap-1.5 rounded-full border border-violet-400/35 bg-violet-400/10 px-2.5 py-1 text-sm font-medium text-violet-300",
            "hover:border-violet-400/55 hover:text-violet-100",
            open && "flex w-full rounded-none border-0 bg-transparent text-violet-100",
            tone === "running" && "border-violet-400/55",
            tone === "fail" && "border-destructive/45 text-[#f0a0a0]",
          )}
        >
          <ChevronRight
            className={cn("size-3.5 shrink-0 transition-transform", open && "rotate-90")}
            aria-hidden
          />
          <Badge
            variant="outline"
            className="h-5 border-0 bg-violet-400/20 px-1.5 font-mono text-[10px] text-violet-300"
          >
            SUB
          </Badge>
          <span className="min-w-0 truncate font-mono text-sm">{summary}</span>
          {item.subagentId ? (
            <span className="ml-auto shrink-0 font-mono text-[10px] text-violet-300/70">
              {item.subagentId}
            </span>
          ) : null}
        </button>
      </CollapsibleTrigger>

      <CollapsibleContent className="grid gap-2 px-2.5 pb-2.5 pt-0.5">
        {item.status === "running" ? <Progress value={58} className="h-0.5" /> : null}
        {item.prompt ? (
          <div>
            <div className="mb-1 text-[10px] uppercase tracking-wide text-violet-300/75">Input</div>
            <pre className="m-0 max-h-[220px] overflow-auto whitespace-pre-wrap break-words rounded-md border border-violet-400/20 bg-black/30 p-2 font-mono text-xs">
              {item.prompt}
            </pre>
          </div>
        ) : null}
        {item.streamText ? (
          <div>
            <div className="mb-1 text-[10px] uppercase tracking-wide text-violet-300/75">
              Output{item.status === "running" ? " (streaming)" : ""}
            </div>
            <pre className="m-0 max-h-[220px] overflow-auto whitespace-pre-wrap break-words rounded-md border border-violet-400/20 bg-black/30 p-2 font-mono text-xs">
              {item.streamText}
            </pre>
          </div>
        ) : null}
        {nestedTools.length ? (
          <div>
            <div className="mb-1 text-[10px] uppercase tracking-wide text-violet-300/75">
              Child tools
            </div>
            <div className="flex flex-col gap-1">
              {nestedTools.map((t, i) => (
                <div
                  key={t.id || i}
                  className={cn(
                    "flex justify-between gap-2 rounded-md border border-violet-400/15 px-2 py-1 font-mono text-[10px] text-muted-foreground",
                    t.status === "ok" && "border-teal/30",
                    t.status === "fail" && "border-destructive/35",
                  )}
                >
                  <span>{t.name}</span>
                  <span>
                    {t.success === false ? "fail" : t.success ? "ok" : "…"}
                  </span>
                </div>
              ))}
            </div>
          </div>
        ) : null}
        {item.error ? (
          <div>
            <div className="mb-1 text-[10px] uppercase tracking-wide text-violet-300/75">Error</div>
            <pre className="m-0 max-h-[220px] overflow-auto whitespace-pre-wrap break-words rounded-md border border-violet-400/20 bg-black/30 p-2 font-mono text-xs">
              {pretty(item.error)}
            </pre>
          </div>
        ) : item.output && item.output !== item.streamText ? (
          <div>
            <div className="mb-1 text-[10px] uppercase tracking-wide text-violet-300/75">Final</div>
            <pre className="m-0 max-h-[220px] overflow-auto whitespace-pre-wrap break-words rounded-md border border-violet-400/20 bg-black/30 p-2 font-mono text-xs">
              {item.output}
            </pre>
          </div>
        ) : null}
        {item.activityId && onInspect ? (
          <div className="flex justify-end">
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="h-6 border-violet-400/30 px-2 text-[10.5px] text-violet-300"
              onClick={(e) => {
                e.stopPropagation();
                onInspect(item.activityId!);
              }}
            >
              查看活动
            </Button>
          </div>
        ) : null}
      </CollapsibleContent>
    </Collapsible>
  );
}

export default SubagentCard;

// web/src/components/SubagentCard.vue
<script setup>
import { computed } from "vue";
import { pretty } from "@/utils/pretty";

const props = defineProps({
  item: { type: Object, required: true },
});
const emit = defineEmits(["inspect"]);

const statusLabel = computed(() => {
  if (props.item.error) return "失败";
  if (props.item.status === "running") return "运行中";
  if (props.item.status === "interrupted") return "已中断";
  if (props.item.status === "idle" || props.item.output) return "完成";
  return props.item.status || "subagent";
});

const summary = computed(() => {
  const parts = [
    props.item.label || props.item.name || "subagent",
    props.item.mode ? String(props.item.mode) : null,
    statusLabel.value,
  ].filter(Boolean);
  return parts.join(" · ");
});

const nestedTools = computed(() => props.item.childTools || []);
</script>

<template>
  <details
    class="subagent-card"
    :class="[item.status || (item.error ? 'fail' : item.output ? 'ok' : 'running')]"
    :open="!!item.open"
    @toggle="item.open = $event.target.open"
  >
    <summary>
      <span class="tool-chevron" aria-hidden="true" />
      <span class="sa-badge">SUB</span>
      <span class="sa-name">{{ summary }}</span>
      <span v-if="item.subagentId" class="sa-meta">{{ item.subagentId }}</span>
    </summary>
    <div class="sa-body">
      <div v-if="item.prompt" class="sa-block">
        <label>Input</label>
        <pre>{{ item.prompt }}</pre>
      </div>
      <div v-if="item.streamText" class="sa-block">
        <label>Output{{ item.status === 'running' ? ' (streaming)' : '' }}</label>
        <pre class="sa-stream">{{ item.streamText }}</pre>
      </div>
      <div v-if="nestedTools.length" class="sa-block">
        <label>Child tools</label>
        <div class="sa-tools">
          <div v-for="(t, i) in nestedTools" :key="t.id || i" class="sa-tool-row" :class="t.status">
            <span class="sa-tool-name">{{ t.name }}</span>
            <span class="sa-tool-meta">{{ t.success === false ? 'fail' : t.success ? 'ok' : '…' }}</span>
          </div>
        </div>
      </div>
      <div v-if="item.error" class="sa-block">
        <label>Error</label>
        <pre>{{ pretty(item.error) }}</pre>
      </div>
      <div v-else-if="item.output && item.output !== item.streamText" class="sa-block">
        <label>Final</label>
        <pre>{{ item.output }}</pre>
      </div>
      <div class="sa-actions">
        <button
          v-if="item.activityId"
          type="button"
          class="tool-inspect"
          @click.stop.prevent="emit('inspect', item.activityId)"
        >
          查看活动
        </button>
      </div>
    </div>
  </details>
</template>

<style scoped>
.subagent-card {
  align-self: flex-start;
  width: fit-content;
  max-width: min(100%, 560px);
  animation: fade 180ms ease both;
}

.subagent-card summary {
  list-style: none;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  gap: 7px;
  padding: 5px 10px;
  font-size: var(--fs-sm);
  font-weight: 500;
  user-select: none;
  border: 1px solid rgba(167, 139, 250, 0.35);
  border-radius: 999px;
  background: rgba(167, 139, 250, 0.08);
  color: #c4b5fd;
}

.subagent-card summary::-webkit-details-marker {
  display: none;
}

.subagent-card summary:hover {
  color: #ede9fe;
  border-color: rgba(167, 139, 250, 0.55);
}

.subagent-card[open] {
  width: min(100%, 560px);
  border: 1px solid rgba(167, 139, 250, 0.35);
  background: rgba(167, 139, 250, 0.07);
  border-radius: var(--radius);
}

.subagent-card[open] summary {
  display: flex;
  width: 100%;
  border: 0;
  border-radius: 0;
  background: transparent;
  color: #ede9fe;
}

.subagent-card.running summary {
  border-color: rgba(167, 139, 250, 0.55);
}

.subagent-card.ok summary {
  border-color: rgba(167, 139, 250, 0.4);
}

.subagent-card.fail summary {
  border-color: rgba(224, 112, 112, 0.45);
  color: #f0a0a0;
}

.sa-badge {
  font-family: var(--mono);
  font-size: var(--fs-xs);
  color: #c4b5fd;
  background: rgba(167, 139, 250, 0.18);
  border-radius: 4px;
  padding: 1px 6px;
}

.sa-name {
  font-family: var(--mono);
  font-size: var(--fs-sm);
}

.sa-meta {
  margin-left: auto;
  font-family: var(--mono);
  font-size: 10px;
  color: rgba(196, 181, 253, 0.7);
}

.sa-body {
  padding: 2px 10px 10px;
  display: grid;
  gap: 8px;
}

.sa-block label {
  display: block;
  font-size: var(--fs-xs);
  color: rgba(196, 181, 253, 0.75);
  margin-bottom: 3px;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}

.sa-block pre,
.sa-stream {
  margin: 0;
  padding: 8px;
  border-radius: 7px;
  background: rgba(0, 0, 0, 0.28);
  border: 1px solid rgba(167, 139, 250, 0.18);
  font-family: var(--mono);
  font-size: var(--fs-xs);
  line-height: 1.4;
  overflow-x: auto;
  white-space: pre-wrap;
  word-break: break-word;
  max-height: 220px;
  color: var(--ink);
}

.sa-tools {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.sa-tool-row {
  display: flex;
  justify-content: space-between;
  gap: 8px;
  padding: 4px 8px;
  border-radius: 6px;
  border: 1px solid rgba(167, 139, 250, 0.15);
  font-family: var(--mono);
  font-size: 10px;
  color: var(--muted);
}

.sa-tool-row.ok {
  border-color: rgba(43, 184, 160, 0.3);
}

.sa-tool-row.fail {
  border-color: rgba(224, 112, 112, 0.35);
}

.sa-actions {
  display: flex;
  justify-content: flex-end;
}

.tool-inspect {
  border: 1px solid rgba(167, 139, 250, 0.3);
  background: transparent;
  color: #c4b5fd;
  font: inherit;
  font-size: var(--fs-xs);
  border-radius: 6px;
  padding: 3px 8px;
  cursor: pointer;
}
</style>
