// web/src/components/tools/WorkspaceToolCard.tsx
import { useMemo, useState } from "react";
import { ChevronRight } from "lucide-react";

import { FileDiffBlock } from "@/components/tools/FileDiffBlock";
import { GenericToolCard, type GenericToolCardProps } from "@/components/tools/GenericToolCard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { lineDiff, writeFileAsDiff } from "@/lib/lineDiff";
import { pretty } from "@/lib/pretty";
import { cn } from "@/lib/utils";

function parseResult(raw: unknown) {
  if (raw == null) return null;
  let data: any = raw;
  if (typeof raw === "string") {
    try {
      data = JSON.parse(raw);
    } catch {
      return null;
    }
  }
  return data && typeof data === "object" ? data : null;
}

function resolveToolKey(name?: string) {
  const n = String(name || "").toLowerCase();
  if (n.includes("grep")) return "grep";
  if (n.includes("glob")) return "glob";
  if (n.includes("list_dir")) return "list_dir";
  if (n.includes("read_file")) return "read_file";
  if (n.includes("write_file")) return "write_file";
  if (n.includes("edit_file")) return "edit_file";
  if (n.includes("run_shell")) return "run_shell";
  return "other";
}

const BADGE_MAP: Record<string, string> = {
  grep: "GREP",
  glob: "GLOB",
  list_dir: "LS",
  read_file: "READ",
  write_file: "WRITE",
  edit_file: "EDIT",
  run_shell: "SHELL",
};

export function WorkspaceToolCard({
  item,
  nested = false,
  onInspect,
  onOpenChange,
}: GenericToolCardProps) {
  const result = useMemo(() => parseResult(item.result), [item.result]);
  const toolKey = resolveToolKey(item.name);
  const [open, setOpen] = useState(!!item.open);

  const badge = BADGE_MAP[toolKey] || item.badge || "TOOL";
  const args = (item.arguments || {}) as Record<string, any>;

  const fileChange = useMemo(() => {
    const path = args.path || result?.path || "";
    if (toolKey === "edit_file" && (args.old_string != null || args.new_string != null)) {
      const diff = lineDiff(args.old_string ?? "", args.new_string ?? "");
      return { path, ...diff, kind: "edit" as const };
    }
    if (toolKey === "write_file" && args.content != null) {
      const diff = writeFileAsDiff(args.content);
      return { path, ...diff, kind: "write" as const };
    }
    return null;
  }, [args, result, toolKey]);

  const summary = useMemo(() => {
    if (item.error) return String(item.error).slice(0, 120);
    if (!result && item.status === "running") return "运行中…";
    switch (toolKey) {
      case "grep":
        return `${args.pattern || ""} · ${result?.match_count ?? (result?.matches || []).length} 处`;
      case "glob":
        return `${args.pattern || ""} · ${(result?.files || []).length} 个文件`;
      case "list_dir":
        return `${args.path || result?.path || "."} · ${(result?.entries || []).length} 项`;
      case "read_file":
        return `${args.path || result?.path || ""} · L${result?.offset || 1}+`;
      case "write_file":
      case "edit_file":
        return args.path || result?.path || "";
      case "run_shell":
        return `exit ${result?.exit_code ?? "?"} · ${String(args.command || "").slice(0, 60)}`;
      default:
        return "";
    }
  }, [args, item.error, item.status, result, toolKey]);

  const previewLines = useMemo(() => {
    if (!result) return [] as string[];
    if (toolKey === "grep") {
      return (result.matches || []).slice(0, 12).map((m: any) => `${m.path}:${m.line}: ${m.text}`);
    }
    if (toolKey === "glob") return (result.files || []).slice(0, 20);
    if (toolKey === "list_dir") {
      return (result.entries || [])
        .slice(0, 20)
        .map((e: any) => `${e.is_dir ? "📁" : "📄"} ${e.name}`);
    }
    if (toolKey === "read_file" && result.content) {
      return String(result.content).split("\n").slice(0, 16);
    }
    if (toolKey === "run_shell") {
      const out = [result.stdout, result.stderr].filter(Boolean).join("\n").trim();
      return out ? out.split("\n").slice(0, 16) : [];
    }
    return [];
  }, [result, toolKey]);

  const useRich = toolKey !== "other" && !!(result || item.arguments);
  const isFileMutation = toolKey === "write_file" || toolKey === "edit_file";
  const mutationStats =
    isFileMutation && !item.error && fileChange?.stats
      ? {
          adds: Number(fileChange.stats.adds || 0),
          dels: Number(fileChange.stats.dels || 0),
        }
      : null;

  if (!useRich) {
    return (
      <GenericToolCard
        item={item}
        nested={nested}
        onInspect={onInspect}
        onOpenChange={onOpenChange}
      />
    );
  }

  const status = item.status || (item.error ? "fail" : "ok");

  return (
    <Collapsible
      open={open}
      onOpenChange={(next) => {
        setOpen(next);
        item.open = next;
        onOpenChange?.(next);
      }}
      className={cn(
        "tool-card w-fit max-w-[min(100%,560px)] self-start rounded-lg border border-border/80 bg-card/40 text-sm",
        nested && "ml-0 w-full max-w-none border-dashed",
        fileChange && "w-full max-w-[min(100%,720px)]",
        status === "ok" && "data-[state=open]:border-teal/40 data-[state=open]:bg-teal/5",
        status === "fail" && "data-[state=open]:border-destructive/40 data-[state=open]:bg-destructive/5",
      )}
    >
      <CollapsibleTrigger asChild>
        <button
          type="button"
          className={cn(
            "flex w-full items-center gap-1.5 px-2 py-1.5 text-left hover:bg-muted/40",
            open && !nested && "border-b border-border/60",
          )}
        >
          <ChevronRight
            className={cn("size-3.5 shrink-0 text-muted-foreground transition-transform", open && "rotate-90")}
            aria-hidden
          />
          <Badge
            variant="outline"
            className={cn(
              "h-5 shrink-0 px-1.5 font-mono text-[10px] font-medium text-[hsl(var(--tool))]",
              (toolKey === "write_file" || toolKey === "edit_file") &&
                "border-emerald-400/35 bg-emerald-600/15 text-[#6ee7b7]",
            )}
          >
            {badge}
          </Badge>
          <span className="min-w-0 flex-1 truncate font-mono text-xs">{item.name}</span>
          <span className="inline-flex min-w-0 shrink-0 items-center gap-2 font-mono text-[10px] text-muted-foreground">
            <span className="min-w-0 truncate">{summary}</span>
            {mutationStats ? (
              <span className="inline-flex shrink-0 gap-1.5 tabular-nums" aria-label="行变更统计">
                {mutationStats.adds ? (
                  <span className="font-semibold text-[#3fb950]">+{mutationStats.adds}</span>
                ) : null}
                {mutationStats.dels ? (
                  <span className="font-semibold text-[#f85149]">−{mutationStats.dels}</span>
                ) : null}
                {!mutationStats.adds && !mutationStats.dels ? (
                  <span className="text-muted-foreground">无变更</span>
                ) : null}
              </span>
            ) : null}
          </span>
        </button>
      </CollapsibleTrigger>
      <CollapsibleContent className="space-y-2 px-2.5 py-2">
        {toolKey === "run_shell" && args.command ? (
          <div className="space-y-1">
            <div className="text-[10px] uppercase tracking-wide text-muted-foreground">Command</div>
            <pre className="max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-md border border-border bg-background/50 p-2 font-mono text-[10.5px]">
              {args.command}
            </pre>
          </div>
        ) : null}

        {fileChange && !item.error ? (
          <FileDiffBlock
            path={fileChange.path}
            rows={fileChange.rows}
            stats={fileChange.stats}
            defaultOpen
          />
        ) : item.arguments &&
          !isFileMutation &&
          !["grep", "glob", "list_dir", "read_file"].includes(toolKey) ? (
          <div className="space-y-1">
            <div className="text-[10px] uppercase tracking-wide text-muted-foreground">Arguments</div>
            <pre className="max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-md border border-border bg-background/50 p-2 font-mono text-[10.5px] text-muted-foreground">
              {pretty(item.arguments)}
            </pre>
          </div>
        ) : null}

        {item.error != null ? (
          <div className="space-y-1">
            <div className="text-[10px] uppercase tracking-wide text-destructive">Error</div>
            <pre className="max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-md border border-destructive/30 bg-destructive/5 p-2 font-mono text-[10.5px]">
              {pretty(item.error)}
            </pre>
          </div>
        ) : previewLines.length ? (
          <div className="space-y-1">
            <div className="text-[10px] uppercase tracking-wide text-muted-foreground">Preview</div>
            <pre className="max-h-[220px] overflow-auto whitespace-pre-wrap break-words rounded-md border border-border bg-background/50 p-2 font-mono text-[10.5px] text-muted-foreground">
              {previewLines.join("\n")}
            </pre>
          </div>
        ) : result && !fileChange ? (
          <div className="space-y-1">
            <div className="text-[10px] uppercase tracking-wide text-muted-foreground">Result</div>
            <pre className="max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-md border border-border bg-background/50 p-2 font-mono text-[10.5px] text-muted-foreground">
              {pretty(result)}
            </pre>
          </div>
        ) : null}

        {item.activityId && onInspect ? (
          <div className="flex justify-end">
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="h-6 px-2 text-[10.5px]"
              onClick={(e) => {
                e.stopPropagation();
                onInspect(item.activityId!);
              }}
            >
              查看活动
            </Button>
          </div>
        ) : null}
      </CollapsibleContent>
    </Collapsible>
  );
}

export default WorkspaceToolCard;

// web/src/components/WorkspaceToolCard.vue
<script setup>
import { computed } from "vue";
import { pretty } from "@/utils/pretty";
import { lineDiff, writeFileAsDiff } from "@/utils/lineDiff";
import FileDiffBlock from "./FileDiffBlock.vue";
import GenericToolCard from "./GenericToolCard.vue";

const props = defineProps({
  item: { type: Object, required: true },
  nested: { type: Boolean, default: false },
});
defineEmits(["inspect"]);

const result = computed(() => {
  let raw = props.item.result;
  if (raw == null) return null;
  if (typeof raw === "string") {
    try {
      raw = JSON.parse(raw);
    } catch {
      return null;
    }
  }
  return raw && typeof raw === "object" ? raw : null;
});

const toolKey = computed(() => {
  const n = String(props.item.name || "").toLowerCase();
  if (n.includes("grep")) return "grep";
  if (n.includes("glob")) return "glob";
  if (n.includes("list_dir")) return "list_dir";
  if (n.includes("read_file")) return "read_file";
  if (n.includes("write_file")) return "write_file";
  if (n.includes("edit_file")) return "edit_file";
  if (n.includes("run_shell")) return "run_shell";
  return "other";
});

const badge = computed(() => {
  const map = {
    grep: "GREP",
    glob: "GLOB",
    list_dir: "LS",
    read_file: "READ",
    write_file: "WRITE",
    edit_file: "EDIT",
    run_shell: "SHELL",
  };
  return map[toolKey.value] || props.item.badge || "TOOL";
});

const fileChange = computed(() => {
  const args = props.item.arguments || {};
  const path = args.path || result.value?.path || "";
  if (toolKey.value === "edit_file" && (args.old_string != null || args.new_string != null)) {
    const diff = lineDiff(args.old_string ?? "", args.new_string ?? "");
    return { path, ...diff, kind: "edit" };
  }
  if (toolKey.value === "write_file" && args.content != null) {
    const diff = writeFileAsDiff(args.content);
    return { path, ...diff, kind: "write" };
  }
  return null;
});

const summary = computed(() => {
  const r = result.value;
  const args = props.item.arguments || {};
  if (props.item.error) return String(props.item.error).slice(0, 120);
  if (!r && props.item.status === "running") return "运行中…";
  switch (toolKey.value) {
    case "grep":
      return `${args.pattern || ""} · ${r?.match_count ?? (r?.matches || []).length} 处`;
    case "glob":
      return `${args.pattern || ""} · ${(r?.files || []).length} 个文件`;
    case "list_dir":
      return `${args.path || r?.path || "."} · ${(r?.entries || []).length} 项`;
    case "read_file":
      return `${args.path || r?.path || ""} · L${r?.offset || 1}+`;
    case "write_file":
    case "edit_file": {
      // Path only — +/− counts render as colored spans in the template.
      return args.path || r?.path || "";
    }
    case "run_shell":
      return `exit ${r?.exit_code ?? "?"} · ${(args.command || "").slice(0, 60)}`;
    default:
      return "";
  }
});

const previewLines = computed(() => {
  const r = result.value;
  if (!r) return [];
  if (toolKey.value === "grep") {
    return (r.matches || []).slice(0, 12).map((m) => `${m.path}:${m.line}: ${m.text}`);
  }
  if (toolKey.value === "glob") {
    return (r.files || []).slice(0, 20);
  }
  if (toolKey.value === "list_dir") {
    return (r.entries || []).slice(0, 20).map((e) => `${e.is_dir ? "📁" : "📄"} ${e.name}`);
  }
  if (toolKey.value === "read_file" && r.content) {
    return String(r.content).split("\n").slice(0, 16);
  }
  if (toolKey.value === "run_shell") {
    const out = [r.stdout, r.stderr].filter(Boolean).join("\n").trim();
    return out ? out.split("\n").slice(0, 16) : [];
  }
  return [];
});

const useRich = computed(() => toolKey.value !== "other" && (result.value || props.item.arguments));
const isFileMutation = computed(() => toolKey.value === "write_file" || toolKey.value === "edit_file");
const mutationStats = computed(() => {
  if (!isFileMutation.value || props.item.error) return null;
  const s = fileChange.value?.stats;
  if (!s) return null;
  return { adds: Number(s.adds || 0), dels: Number(s.dels || 0) };
});
</script>

<template>
  <GenericToolCard
    v-if="!useRich"
    :item="item"
    :nested="nested"
    @inspect="$emit('inspect', $event)"
  />
  <details
    v-else
    class="tool-card"
    :class="[
      item.status || (item.error ? 'fail' : 'ok'),
      { nested, 'has-diff': !!fileChange },
    ]"
    :open="!!item.open"
    @toggle="item.open = $event.target.open"
  >
    <summary>
      <span class="tool-chevron" aria-hidden="true" />
      <span class="tool-badge" :class="toolKey">{{ badge }}</span>
      <span class="tool-name">{{ item.name }}</span>
      <span class="tool-meta">
        <span class="tool-meta-path">{{ summary }}</span>
        <span v-if="mutationStats" class="tool-diff-stats" aria-label="行变更统计">
          <span v-if="mutationStats.adds" class="stat-add">+{{ mutationStats.adds }}</span>
          <span v-if="mutationStats.dels" class="stat-del">−{{ mutationStats.dels }}</span>
          <span v-if="!mutationStats.adds && !mutationStats.dels" class="stat-none">无变更</span>
        </span>
      </span>
    </summary>
    <div class="tool-body">
      <div v-if="toolKey === 'run_shell' && item.arguments?.command" class="tool-block">
        <label>Command</label>
        <pre>{{ item.arguments.command }}</pre>
      </div>

      <FileDiffBlock
        v-if="fileChange && !item.error"
        class="file-diff-slot"
        :path="fileChange.path"
        :rows="fileChange.rows"
        :stats="fileChange.stats"
        :default-open="true"
      />

      <div
        v-else-if="item.arguments && !isFileMutation && !['grep', 'glob', 'list_dir', 'read_file'].includes(toolKey)"
        class="tool-block"
      >
        <label>Arguments</label>
        <pre>{{ pretty(item.arguments) }}</pre>
      </div>

      <div v-if="item.error" class="tool-block">
        <label>Error</label>
        <pre>{{ pretty(item.error) }}</pre>
      </div>
      <div v-else-if="previewLines.length" class="tool-block">
        <label>Preview</label>
        <pre class="preview">{{ previewLines.join("\n") }}</pre>
      </div>
      <div v-else-if="result && !fileChange" class="tool-block">
        <label>Result</label>
        <pre>{{ pretty(result) }}</pre>
      </div>

      <div class="tool-actions">
        <button
          v-if="item.activityId"
          type="button"
          class="tool-inspect"
          @click.stop.prevent="$emit('inspect', item.activityId)"
        >
          查看活动
        </button>
      </div>
    </div>
  </details>
</template>

<style scoped>
.preview {
  max-height: 220px;
  overflow: auto;
}
.tool-actions {
  display: flex;
  justify-content: flex-end;
}
.tool-inspect {
  border: 1px solid var(--line);
  background: transparent;
  color: var(--muted);
  font: inherit;
  font-size: var(--fs-xs);
  border-radius: 6px;
  padding: 3px 8px;
  cursor: pointer;
}
.tool-inspect:hover {
  color: var(--ink);
  border-color: rgba(58, 156, 240, 0.4);
}
.file-diff-slot {
  margin-top: 2px;
}
.tool-card.has-diff {
  max-width: min(100%, 720px);
  width: 100%;
}
.tool-badge.write_file,
.tool-badge.edit_file {
  color: #6ee7b7;
  border-color: rgba(110, 231, 183, 0.35);
  background: rgba(46, 160, 67, 0.12);
}

.tool-meta {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.tool-meta-path {
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.tool-diff-stats {
  display: inline-flex;
  gap: 6px;
  flex-shrink: 0;
  font-family: var(--mono);
  font-variant-numeric: tabular-nums;
}

.tool-diff-stats .stat-add {
  color: #3fb950;
  font-weight: 600;
}

.tool-diff-stats .stat-del {
  color: #f85149;
  font-weight: 600;
}

.tool-diff-stats .stat-none {
  color: var(--muted);
}
</style>
